kind: ClusterRoleBinding # Kind not allowed, so not "syncable"
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jamal-rolebinding
subjects:
- kind: User
  name: alice@acme.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: acme-admin
  apiGroup: rbac.authorization.k8s.io
