kind: Role # kind not allowed
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: no-such-cluster-selector
  annotations:
    config.gke.io/cluster-selector: nonexistent-selector  # this selector does not exist.
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list"]
