// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	apis "github.com/google/nomos/clientgen/apis"
	internalinterfaces "github.com/google/nomos/clientgen/informer/internalinterfaces"
	v1 "github.com/google/nomos/clientgen/listers/configmanagement/v1"
	configmanagementv1 "github.com/google/nomos/pkg/api/configmanagement/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HierarchicalQuotaInformer provides access to a shared informer and lister for
// HierarchicalQuotas.
type HierarchicalQuotaInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.HierarchicalQuotaLister
}

type hierarchicalQuotaInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewHierarchicalQuotaInformer constructs a new informer for HierarchicalQuota type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHierarchicalQuotaInformer(client apis.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHierarchicalQuotaInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredHierarchicalQuotaInformer constructs a new informer for HierarchicalQuota type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHierarchicalQuotaInformer(client apis.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfigmanagementV1().HierarchicalQuotas().List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfigmanagementV1().HierarchicalQuotas().Watch(options)
			},
		},
		&configmanagementv1.HierarchicalQuota{},
		resyncPeriod,
		indexers,
	)
}

func (f *hierarchicalQuotaInformer) defaultInformer(client apis.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHierarchicalQuotaInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hierarchicalQuotaInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&configmanagementv1.HierarchicalQuota{}, f.defaultInformer)
}

func (f *hierarchicalQuotaInformer) Lister() v1.HierarchicalQuotaLister {
	return v1.NewHierarchicalQuotaLister(f.Informer().GetIndexer())
}
