apiVersion: v1
kind: Service
metadata:
  labels:
    bespin.dev/system: "true"
  name: bespin-controllers-manager-service
  namespace: nomos-system
spec:
  ports:
  - port: 443
  selector:
    bespin.dev/system: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    bespin.dev/system: "true"
  name: bespin-controllers-manager
  namespace: nomos-system
spec:
  selector:
    matchLabels:
      bespin.dev/system: "true"
  serviceName: bespin-controllers-manager-service
  template:
    metadata:
      labels:
        bespin.dev/system: "true"
    spec:
      serviceAccountName: bespin-controllers-manager
      containers:
      - image: ${IMAGE_NAME}
        name: bespin-controllers-manager
        command: [
          "/bespin/bespin-controllers-manager",
          "-alsologtostderr=true",
          "-v=10",
        ]
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 900Mi
      terminationGracePeriodSeconds: 10
