# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- reposync-crd.yaml
- rootsync-crd.yaml

patchesStrategicMerge:
- |-
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    creationTimestamp:
      $patch: delete
    name: rootsyncs.configsync.gke.io
    labels:
      configmanagement.gke.io/system: "true"
      configmanagement.gke.io/arch: "csmr"
  spec:
    preserveUnknownFields: false
  status:
    $patch: delete
- |-
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    creationTimestamp:
      $patch: delete
    name: reposyncs.configsync.gke.io
    labels:
      configmanagement.gke.io/system: "true"
      configmanagement.gke.io/arch: "csmr"
  spec:
    preserveUnknownFields: false
  status:
    $patch: delete