apiVersion: "settings.k8s.io/v1"
kind: PolicyNode
metadata:
  name: policy-node-ns2
spec:
  Name: nameSpace2
  WorkingNamespace: true
  Parent: orgUnit1
  Policies:
    ResourceQuotas:
    - kind: ResourceQuota
      apiVersion: v1
      metadata:
        namespace: nameSpace2
        name: object-counts
      spec:
        hard:
          services: "10"
