apiVersion: "k8us.k8s.io/v1"
kind: PolicyNode
metadata:
  name: twix-corp
spec:
  policyspace: true
  policies:
    resourceQuota:
      hard:
        configmaps: "1"
---
apiVersion: "k8us.k8s.io/v1"
kind: PolicyNode
metadata:
  name: left-twix
spec:
  policyspace: false
  parent: twix-corp
  policies:
    resourceQuota:
      hard:
        pods: "7"
        configmaps: "10"
---
apiVersion: "k8us.k8s.io/v1"
kind: PolicyNode
metadata:
  name: right-twix
spec:
  policyspace: false
  parent: twix-corp
  policies:
    resourceQuota:
      hard:
        configmaps: "0"
