apiVersion: v1
kind: Pod
metadata:
        name: authorizer
spec:
        containers:
        - name: authorizer
          image: authorizer:experimental
          ports:
                - containerPort: 443
          args: ["--logtostderr"]

