# Constraints on the vendor directory and deps.
#
# If you introduce a rule below, please make a note why the rule exists.
# Sometimes it is far from obvious.
#
# File syntax docs at: https://golang.github.io/dep/docs/Gopkg.toml.html


[prune]
  go-tests = true
  unused-packages = true

  # json-iterator/go does some weird symlink stuff with a unit test
  # which causes gomvpkg to not work.
  [[prune.project]]
    name = "github.com/json-iterator/go"
    go-tests = false

# Pin the version of a k8s package to ensure that libraries are migrated to
# this version.  Versions should match across packages.
[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.12"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.4.0"

# Pin the version of a k8s package to ensure that libraries are migrated to
# this version.  Versions should match across packages.
[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.12"

# Pin the version of a k8s package to ensure that libraries are migrated to
# this version.  Versions should match across packages.
[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.12"

# Pin the version of a k8s package to ensure that libraries are migrated to
# this version.  Versions should match across packages.
[[constraint]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.13.12"

# Pin the version of a k8s package to ensure that libraries are migrated to
# this version.  Versions should match across packages.
[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.12"

# Pin the version of a k8s package to ensure that libraries are migrated to
# this version.  Versions should match across packages.
[[constraint]]
  name = "k8s.io/kubectl"
  version = "kubernetes-1.16.3"

# Required for vendoring apimachinery
[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

# Not fixing the branch gets us the package from branches other than master
# which is weird.
[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

# Not fixing the branch gets us the package from branches other than master
# which is weird.
[[override]]
  branch = "master"
  name = "github.com/looplab/tarjan"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"

# Needed for client-go.
[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v10.15.4"

# It is useful to pin down a large dependency.
[[override]]
  name = "github.com/docker/distribution"
  version = "v2.7.1"

##############################################################################

# Constraints below need to be reexamined.  Either because they are unknown, or
# because they may no longer apply.

[[constraint]]
  revision = "97aa668b73e764ccdd786bc3ccd2edffe621150e"
  name = "github.com/google/go-cmp"

# Markdown processor.
# TODO(fmil): Why is the version pinned?
[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.4-2-g300106c"

