/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1

import (
	v1 "github.com/google/stolos/pkg/api/policyhierarchy/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// StolosRoleBindingLister helps list StolosRoleBindings.
type StolosRoleBindingLister interface {
	// List lists all StolosRoleBindings in the indexer.
	List(selector labels.Selector) (ret []*v1.StolosRoleBinding, err error)
	// StolosRoleBindings returns an object that can list and get StolosRoleBindings.
	StolosRoleBindings(namespace string) StolosRoleBindingNamespaceLister
	StolosRoleBindingListerExpansion
}

// stolosRoleBindingLister implements the StolosRoleBindingLister interface.
type stolosRoleBindingLister struct {
	indexer cache.Indexer
}

// NewStolosRoleBindingLister returns a new StolosRoleBindingLister.
func NewStolosRoleBindingLister(indexer cache.Indexer) StolosRoleBindingLister {
	return &stolosRoleBindingLister{indexer: indexer}
}

// List lists all StolosRoleBindings in the indexer.
func (s *stolosRoleBindingLister) List(selector labels.Selector) (ret []*v1.StolosRoleBinding, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.StolosRoleBinding))
	})
	return ret, err
}

// StolosRoleBindings returns an object that can list and get StolosRoleBindings.
func (s *stolosRoleBindingLister) StolosRoleBindings(namespace string) StolosRoleBindingNamespaceLister {
	return stolosRoleBindingNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// StolosRoleBindingNamespaceLister helps list and get StolosRoleBindings.
type StolosRoleBindingNamespaceLister interface {
	// List lists all StolosRoleBindings in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.StolosRoleBinding, err error)
	// Get retrieves the StolosRoleBinding from the indexer for a given namespace and name.
	Get(name string) (*v1.StolosRoleBinding, error)
	StolosRoleBindingNamespaceListerExpansion
}

// stolosRoleBindingNamespaceLister implements the StolosRoleBindingNamespaceLister
// interface.
type stolosRoleBindingNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all StolosRoleBindings in the indexer for a given namespace.
func (s stolosRoleBindingNamespaceLister) List(selector labels.Selector) (ret []*v1.StolosRoleBinding, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.StolosRoleBinding))
	})
	return ret, err
}

// Get retrieves the StolosRoleBinding from the indexer for a given namespace and name.
func (s stolosRoleBindingNamespaceLister) Get(name string) (*v1.StolosRoleBinding, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("stolosrolebinding"), name)
	}
	return obj.(*v1.StolosRoleBinding), nil
}
