kind: Sync
apiVersion: nomos.dev/v1alpha1
metadata:
  name: invalid
spec:
  groups:
  - group: unknown.group.com
    kinds:
    - kind: Unknown
      versions:
      - version: v1
  - group: extensions
    kinds:
    - kind: CustomResourceDefinition
      versions:
      - version: v1beta1
  - group: nomos.dev
    kinds:
    - kind: PolicyNode
      versions:
      - version: v1
    - kind: Sync
      versions:
      - version: v1alpha1