// Code generated by cmd/gen-core-scoper/main.go. DO NOT EDIT

package discovery

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// CoreScoper returns a Scoper with the scopes of all core Kubernetes and Nomos
// types defined. Use this instead of building a Scoper from the response to an
// APIServer when one is unavailable.
func CoreScoper() Scoper {
	return map[schema.GroupKind]IsNamespaced{
		schema.GroupKind{Group: "", Kind: "ConfigMap"}:                                                  NamespaceScope,
		schema.GroupKind{Group: "", Kind: "Endpoints"}:                                                  NamespaceScope,
		schema.GroupKind{Group: "", Kind: "Event"}:                                                      NamespaceScope,
		schema.GroupKind{Group: "", Kind: "LimitRange"}:                                                 NamespaceScope,
		schema.GroupKind{Group: "", Kind: "Namespace"}:                                                  ClusterScope,
		schema.GroupKind{Group: "", Kind: "Node"}:                                                       ClusterScope,
		schema.GroupKind{Group: "", Kind: "PersistentVolumeClaim"}:                                      NamespaceScope,
		schema.GroupKind{Group: "", Kind: "PersistentVolume"}:                                           ClusterScope,
		schema.GroupKind{Group: "", Kind: "Pod"}:                                                        NamespaceScope,
		schema.GroupKind{Group: "", Kind: "PodTemplate"}:                                                NamespaceScope,
		schema.GroupKind{Group: "", Kind: "ReplicationController"}:                                      NamespaceScope,
		schema.GroupKind{Group: "", Kind: "ResourceQuota"}:                                              NamespaceScope,
		schema.GroupKind{Group: "", Kind: "Secret"}:                                                     NamespaceScope,
		schema.GroupKind{Group: "", Kind: "ServiceAccount"}:                                             NamespaceScope,
		schema.GroupKind{Group: "", Kind: "Service"}:                                                    NamespaceScope,
		schema.GroupKind{Group: "admissionregistration.k8s.io", Kind: "MutatingWebhookConfiguration"}:   ClusterScope,
		schema.GroupKind{Group: "admissionregistration.k8s.io", Kind: "ValidatingWebhookConfiguration"}: ClusterScope,
		schema.GroupKind{Group: "apiextensions.k8s.io", Kind: "CustomResourceDefinition"}:               ClusterScope,
		schema.GroupKind{Group: "apiregistration.k8s.io", Kind: "APIService"}:                           ClusterScope,
		schema.GroupKind{Group: "apps", Kind: "ControllerRevision"}:                                     NamespaceScope,
		schema.GroupKind{Group: "apps", Kind: "DaemonSet"}:                                              NamespaceScope,
		schema.GroupKind{Group: "apps", Kind: "Deployment"}:                                             NamespaceScope,
		schema.GroupKind{Group: "apps", Kind: "ReplicaSet"}:                                             NamespaceScope,
		schema.GroupKind{Group: "apps", Kind: "StatefulSet"}:                                            NamespaceScope,
		schema.GroupKind{Group: "autoscaling", Kind: "HorizontalPodAutoscaler"}:                         NamespaceScope,
		schema.GroupKind{Group: "batch", Kind: "CronJob"}:                                               NamespaceScope,
		schema.GroupKind{Group: "batch", Kind: "Job"}:                                                   NamespaceScope,
		schema.GroupKind{Group: "certificates.k8s.io", Kind: "CertificateSigningRequest"}:               ClusterScope,
		schema.GroupKind{Group: "cloud.google.com", Kind: "BackendConfig"}:                              NamespaceScope,
		schema.GroupKind{Group: "coordination.k8s.io", Kind: "Lease"}:                                   NamespaceScope,
		schema.GroupKind{Group: "extensions", Kind: "DaemonSet"}:                                        NamespaceScope,
		schema.GroupKind{Group: "extensions", Kind: "Deployment"}:                                       NamespaceScope,
		schema.GroupKind{Group: "extensions", Kind: "Ingress"}:                                          NamespaceScope,
		schema.GroupKind{Group: "extensions", Kind: "NetworkPolicy"}:                                    NamespaceScope,
		schema.GroupKind{Group: "extensions", Kind: "PodSecurityPolicy"}:                                ClusterScope,
		schema.GroupKind{Group: "extensions", Kind: "ReplicaSet"}:                                       NamespaceScope,
		schema.GroupKind{Group: "networking.gke.io", Kind: "ManagedCertificate"}:                        NamespaceScope,
		schema.GroupKind{Group: "networking.k8s.io", Kind: "NetworkPolicy"}:                             NamespaceScope,
		schema.GroupKind{Group: "nodemanagement.gke.io", Kind: "UpdateInfo"}:                            NamespaceScope,
		schema.GroupKind{Group: "policy", Kind: "PodDisruptionBudget"}:                                  NamespaceScope,
		schema.GroupKind{Group: "policy", Kind: "PodSecurityPolicy"}:                                    ClusterScope,
		schema.GroupKind{Group: "rbac.authorization.k8s.io", Kind: "ClusterRoleBinding"}:                ClusterScope,
		schema.GroupKind{Group: "rbac.authorization.k8s.io", Kind: "ClusterRole"}:                       ClusterScope,
		schema.GroupKind{Group: "rbac.authorization.k8s.io", Kind: "RoleBinding"}:                       NamespaceScope,
		schema.GroupKind{Group: "rbac.authorization.k8s.io", Kind: "Role"}:                              NamespaceScope,
		schema.GroupKind{Group: "scalingpolicy.kope.io", Kind: "ScalingPolicy"}:                         NamespaceScope,
		schema.GroupKind{Group: "scheduling.k8s.io", Kind: "PriorityClass"}:                             ClusterScope,
		schema.GroupKind{Group: "storage.k8s.io", Kind: "StorageClass"}:                                 ClusterScope,
		schema.GroupKind{Group: "storage.k8s.io", Kind: "VolumeAttachment"}:                             ClusterScope,
	}
}
