apiVersion: "stolos.dev/v1"
kind: PolicyNode
metadata:
  name: acme
spec:
  policyspace: true
  policies:
    resourceQuota:
      hard:
        secrets: "10"
    roles:
    - kind: Role
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        namespace: acme
        name: acme-admin
      rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["*"]
      - apiGroups: [""]
        resources: ["namespaces"]
        verbs: ["get"]
      - apiGroups: ["rbac.authorization.k8s.io"]
        resources: ["roles", "rolebindings"]
        verbs: ["get", "list"]
---
apiVersion: "stolos.dev/v1"
kind: PolicyNode
metadata:
  name: eng
spec:
  policyspace: true
  parent: acme
  policies:
    resourceQuota:
      hard:
        pods: "1"
        secrets: "5"
    rolebindings:
    - kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        namespace: eng
        name: alice-rolebinding
      subjects:
      - kind: User
        name: alice@acme.com
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: Role
        name: acme-admin
        apiGroup: rbac.authorization.k8s.io
---
apiVersion: "stolos.dev/v1"
kind: PolicyNode
metadata:
  name: rnd
spec:
  policyspace: true
  parent: acme
  policies:
    resourceQuota:
      hard:
        configmaps: "2"
---
apiVersion: "stolos.dev/v1"
kind: PolicyNode
metadata:
  name: backend
spec:
  policyspace: false
  parent: eng
  policies:
    resourceQuota:
      hard:
        pods: "1"
    rolebindings:
    - kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        namespace: backend
        name: bob-rolebinding
      subjects:
      - kind: User
        name: bob@acme.com
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: Role
        name: acme-admin
        apiGroup: rbac.authorization.k8s.io
---
apiVersion: "stolos.dev/v1"
kind: PolicyNode
metadata:
  name: frontend
spec:
  policyspace: false
  parent: eng
  policies:
    resourceQuota:
      hard:
        pods: "1"
---
apiVersion: "stolos.dev/v1"
kind: PolicyNode
metadata:
  name: new-prj
spec:
  policyspace: false
  parent: rnd
---
apiVersion: "stolos.dev/v1"
kind: PolicyNode
metadata:
  name: newer-prj
spec:
  policyspace: false
  parent: rnd
---
# Example for clusterroles
apiVersion: "stolos.dev/v1"
kind: ClusterPolicy
metadata:
  name: clusterrole
spec:
  policies:
    type: clusterrole
    clusterRoles:
    - kind: ClusterRole
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: namespace-viewer
      rules:
      - apiGroups: [""]
        resources: ["namespaces"]
        verbs: ["get", "list"]
    - kind: ClusterRole
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: rbac-viewer
      rules:
      - apiGroups: ["rbac.authorization.k8s.io"]
        resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
        verbs: ["get", "list"]
---
# Example for clusterrolebindings
apiVersion: "stolos.dev/v1"
kind: ClusterPolicy
metadata:
  name: clusterrolebinding
spec:
  policies:
    type: clusterrolebinding
    clusterRoleBindings:
    - kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: namespace-viewers
      subjects:
      - kind: User
        name: cheryl@acme.com
        apiGroup: rbac.authorization.k8s.io
      - kind: User
        name: cyril@acme.com
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: namespace-viewer
        apiGroup: rbac.authorization.k8s.io
    - kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: rbac-viewers
      subjects:
      - kind: User
        name: cheryl@acme.com
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: rbac-viewer
        apiGroup: rbac.authorization.k8s.io
---
# Example for podsecuirtypolicy
apiVersion: "stolos.dev/v1"
kind: ClusterPolicy
metadata:
  name: podsecuritypolicy
spec:
  policies:
    type: podsecuritypolicy
    podSecurityPolicy:
    - kind: PodSecurityPolicy
      apiVersion: extensions/v1beta1
      metadata:
        name: example
      spec:
        privileged: false
        seLinux:
          rule: RunAsAny
        supplementalGroups:
          rule: RunAsAny
        runAsUser:
          rule: RunAsAny
        fsGroup:
          rule: RunAsAny
        volumes:
        - '*'
