changecom(`<unused>')
# Reviewed by sunilarora
apiVersion: v1
kind: Service
metadata:
  name: git-policy-importer
  namespace: nomos-system
  labels:
    monitored: "true"
spec:
  selector:
    app: git-policy-importer
  ports:
    - name: metrics
      port: 8675
      targetPort: metrics-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-policy-importer
  namespace: nomos-system
  labels:
    app: git-policy-importer
spec:
  minReadySeconds: 10
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: git-policy-importer
  template:
    metadata:
      labels:
        app: git-policy-importer
    spec:
      serviceAccountName: policy-importer
      containers:
      - name: policy-importer
        image: IMAGE_NAME
        ports:
          - containerPort: 8675
            name: metrics-port
        volumeMounts:
          - name: repo
            mountPath: /repo
            readOnly: true
        envFrom:
          - configMapRef:
              name: git-policy-importer
      - name: git-sync
        image: gcr.io/nomos-release/git-sync-amd64:v2.0.6-7-gd26f48d
        args: ["--root=/repo", "--dest=rev"]
        volumeMounts:
        - name: repo
          mountPath: /repo
        - name: git-creds
          mountPath: /etc/git-secret
          readOnly: true
        securityContext:
          runAsUser: 0
        envFrom:
          - configMapRef:
              name: git-policy-importer
      volumes:
      - name: repo
      - name: git-creds
        secret:
          secretName: git-creds
          defaultMode: 256

