changecom(`<unused>')
apiVersion: v1
kind: Service
metadata:
  name: nomosresourcequota
  namespace: nomos-system
  labels:
    monitored: "true"
spec:
  selector:
    app: nomosresourcequota
  ports:
    - name: web
      port: 80
      targetPort: web-port
    - name: metrics
      port: 8675
      targetPort: metrics-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nomosresourcequota-controller
  namespace: nomos-system
  labels:
    app: nomosresourcequota
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nomosresourcequota
  template:
    metadata:
      labels:
        app: nomosresourcequota
    spec:
      serviceAccountName: nomosresourcequota-controller
      containers:
        - name: nomosresourcequota-controller
          image: IMAGE_NAME
          ports:
            - containerPort: 80
              name: web-port
            - containerPort: 8675
              name: metrics-port
