changecom(`<unused>')
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-cluster-policy-importer
  namespace: stolos-system
  labels:
    apps: remote-cluster-policy-importer
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      apps: remote-cluster-policy-importer
  template:
    metadata:
      labels:
        apps: remote-cluster-policy-importer
    spec:
      serviceAccountName: policy-importer
      containers:
      - name: remote-cluster-policy-importer
        image: IMAGE_NAME
        env:
          - name: REMOTE_KUBERNETES_API_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: remote-cluster-policy-importer
                namespace: stolos-system
                key: master.endpoint
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: "/etc/stolos/secrets/master"
      volumes:
      - name: secret-volume
        secret:
          secretName: remote-cluster-policy-importer-master-secret