changecom(`<unused>')
apiVersion: v1
kind: Service
metadata:
  name: syncer
  namespace: stolos-system
  labels:
    monitored: "true"
spec:
  selector:
    app: syncer
  ports:
    - name: web
      port: 80
      targetPort: web-port
    - name: metrics
      port: 8675
      targetPort: metrics-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncer
  namespace: stolos-system
  labels:
    app: syncer
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: syncer
  template:
    metadata:
      labels:
        app: syncer
    spec:
      serviceAccountName: syncer
      containers:
        - name: syncer
          image: IMAGE_NAME
          ports:
            - containerPort: 80
              name: web-port
            - containerPort: 8675
              name: metrics-port
