# Custom Resource Definition for a Cluster Selector.
# This is by and large identical spec to NamespaceSelector, but used in a
# different context.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterselectors.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
spec:
  preserveUnknownFields: false
  group: configmanagement.gke.io
  scope: Cluster
  names:
    plural: clusterselectors
    singular: clusterselector
    kind: ClusterSelector
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        # TODO(frankf): Complete and tests this once 1.11 beta is out.
        openAPIV3Schema:
          type: object
          required:
          - spec
          properties:
            spec:
              # ClusterSelectorSpec
              type: object
              required:
              - selector
              properties:
                selector:
                  type: object # metav1.LabelSelector
                  x-kubernetes-preserve-unknown-fields: true
              # /ClusterSelectorSpec
