# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Custom Resource Definition for a Cluster Selector.
# This is by and large identical spec to NamespaceSelector, but used in a
# different context.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterselectors.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
spec:
  preserveUnknownFields: false
  group: configmanagement.gke.io
  scope: Cluster
  names:
    plural: clusterselectors
    singular: clusterselector
    kind: ClusterSelector
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        # TODO(frankf): Complete and tests this once 1.11 beta is out.
        openAPIV3Schema:
          type: object
          required:
          - spec
          properties:
            spec:
              # ClusterSelectorSpec
              type: object
              required:
              - selector
              properties:
                selector:
                  type: object # metav1.LabelSelector
                  x-kubernetes-preserve-unknown-fields: true
              # /ClusterSelectorSpec
