# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Custom Resource Definition for ClusterConfig
# which manages cluster level configs on the
# kubernetes cluster.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterconfigs.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "legacy"
spec:
  preserveUnknownFields: false
  group: configmanagement.gke.io
  scope: Cluster
  names:
    plural: clusterconfigs
    singular: clusterconfig
    kind: ClusterConfig
    shortNames:
    - cr
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            # ClusterConfigSpec
            type: object
            properties:
              token:
                type: string
              importTime: # metav1.Time
                type: string
                format: date-time
                nullable: true
              resources:
                type: array
                items:
                  # GenericResources
                  type: object
                  required:
                  - kind
                  - versions
                  properties:
                    group:
                      type: string
                    kind:
                      type: string
                    versions:
                      type: array
                      items:
                        # GenericVersionResources
                        type: object
                        required:
                        - objects
                        - version
                        properties:
                          objects:
                            type: array
                            items:
                              type: object # runtime.RawExtension
                              x-kubernetes-embedded-resource: true
                              x-kubernetes-preserve-unknown-fields: true
                          version:
                            type: string
                        # /GenericVersionResources
                  # /GenericResources
            # /ClusterConfigSpec
          status:
            # ClusterConfigStatus
            type: object
            properties:
              token:
                type: string
              syncErrors:
                type: array
                items:
                  # ClusterConfigSyncError
                  type: object
                  properties:
                    sourcePath:
                      type: string
                    resourceName:
                      type: string
                    resourceNamespace:
                      type: string
                    resourceGVK: # schema.GroupVersionKind
                      type: object
                      properties:
                        Group:
                          type: string
                        Version:
                          type: string
                        Kind:
                          type: string
                    code:
                      type: string
                    errorMessage:
                      type: string
                    errorResources:
                      type: array
                      items:
                        type: object
                        properties:
                          sourcePath:
                            type: string
                          resourceName:
                            type: string
                          resourceNamespace:
                            type: string
                          resourceGVK:
                            type: object # schema.GroupVersionKind
                            properties:
                              Group:
                                type: string
                              Version:
                                type: string
                              Kind:
                                type: string
                  # /ClusterConfigSyncError
              syncTime: # metav1.Time
                type: string
                format: date-time
                nullable: true
              syncState:
                type: string
                enum:
                - ""
                - "synced"
                - "stale"
                - "error"
              resourceConditions:
                type: array
                items:
                  type: object
                  properties:
                    groupVersion:
                      type: string
                    kind:
                      type: string
                    namespacedName:
                      type: string
                    resourceState:
                      type: string
                    token:
                      type: string
                    reconcilingReasons:
                      type: array
                      items:
                        type: string
                    errors:
                      type: array
                      items:
                        type: string
            # /ClusterConfigStatus
