# Custom Resource Definition for ClusterPolicy
# which manages cluster level policies on the
# kubernetes cluster.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterpolicies.nomos.dev
  labels:
    configmanagement.gke.io/system: "true"
spec:
  group: nomos.dev
  version: v1
  scope: Cluster
  names:
    plural: clusterpolicies
    singular: clusterpolicy
    kind: ClusterPolicy
    shortNames:
    - cp
  subresources:
    status: {}
  validation:
      openAPIV3Schema:
        required:
        - spec
        properties:
          spec:
            # ClusterPolicySpec
            type: object
            properties:
              importToken:
                type: string
              importTime: # metav1.Time
                anyOf:
                - format: date-time
                  type: string
                - {}
              resources:
                type: array
                items:
                  # GenericResources
                  type: object
                  required:
                  - kind
                  - versions
                  properties:
                    group:
                      type: string
                    kind:
                      type: string
                    versions:
                      type: array
                      items:
                        # GenericVersionResources
                        type: object
                        required:
                        - objects
                        - version
                        properties:
                          objects:
                            type: array
                            items:
                              type: object # runtime.RawExtension
                          version:
                            type: string
                        # /GenericVersionResources
                  # /GenericResources
            # /ClusterPolicySpec
          status:
            # ClusterPolicyStatus
            type: object
            properties:
              syncToken:
                type: string
              syncErrors:
                type: array
                items:
                  # ClusterPolicySyncError
                  type: object
                  properties:
                    resourceName:
                      type: string
                    resourceKind:
                      type: string
                    resourceAPI:
                      type: string
                    errorMessage:
                      type: string
                  # /ClusterPolicySyncError
              syncTime: # metav1.Time
                anyOf:
                - format: date-time
                  type: string
                - {}
              syncState:
                type: string
                enum:
                - ""
                - "synced"
                - "stale"
                - "error"
            # /ClusterPolicyStatus
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
