# Custom Resource Definition for ClusterConfig
# which manages cluster level configs on the
# kubernetes cluster.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterconfigs.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
spec:
  group: configmanagement.gke.io
  scope: Cluster
  names:
    plural: clusterconfigs
    singular: clusterconfig
    kind: ClusterConfig
    shortNames:
    - cr
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
