apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stolos-service-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - resourcequotas
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - k8us.k8s.io
  resources:
  - policynodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8us.k8s.io
  resources:
  - stolosresourcequotas
  verbs:
  - "*"