# Custom Resource Definition for a Cluster Selector.
# This is by and large identical spec to NamespaceSelector, but used in a
# different context.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterselectors.nomos.dev
  labels:
    configmanagement.gke.io/system: "true"
spec:
  group: nomos.dev
  version: v1
  scope: Cluster
  names:
    plural: clusterselectors
    singular: clusterselector
    kind: ClusterSelector
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
   # TODO(frankf): Complete and tests this once 1.11 beta is out.
    openAPIV3Schema:
      required:
      - spec
      properties:
        spec:
          # ClusterSelectorSpec
          type: object
          required:
          - selector
          properties:
            selector:
              type: object # metav1.LabelSelector
          # /ClusterSelectorSpec
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
