# Custom Resource Definition for a declaring the hierarchy mode for resources
# in the source of truth.
# See pkg/api/configmanagement/v1alpha1/types.go for the CRD struct spec.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hierarchyconfigs.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
spec:
  group: configmanagement.gke.io
  scope: Cluster
  names:
    plural: hierarchyconfigs
    singular: hierarchyconfig
    kind: HierarchyConfig
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
