# Custom Resource Definition for a declaring the hierarchy mode for resources
# in the source of truth.
# See pkg/api/policyhierarchy/v1alpha1/types.go for the CRD struct spec.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hierarchyconfigs.nomos.dev
  labels:
    config.gke.io/system: "true"
spec:
  group: nomos.dev
  version: v1
  scope: Cluster
  names:
    plural: hierarchyconfigs
    singular: hierarchyconfig
    kind: HierarchyConfig
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []