# Nomos importer service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: importer
  namespace: config-management-system
---
# Importer needs to run as cluster-admin in order to be able to set RBAC
# permissions due to the restriction that you must have a permission in order
# to set it. This seems fine given that the importer is effectively administering
# the cluster.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmanagement.gke.io:importer
  labels:
    configmanagement.gke.io/system: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # Note that running as cluster-admin means the SA does not need a PodSecurityPolicy.
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: importer
  namespace: config-management-system
