# Nomos monitor service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor
  namespace: config-management-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nomos.dev:monitor
  labels:
    config.gke.io/system: "true"
rules:
- apiGroups:
  - nomos.dev
  resources:
  - policynodes
  - clusterpolicies
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nomos.dev:monitor
  labels:
    config.gke.io/system: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nomos.dev:monitor
subjects:
- kind: ServiceAccount
  name: monitor
  namespace: config-management-system
