# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Nomos monitor service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor
  namespace: config-management-system
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "legacy"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmanagement.gke.io:monitor
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "legacy"
rules:
- apiGroups:
  - configmanagement.gke.io
  resources:
  - namespaceconfigs
  - clusterconfigs
  - repos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
    - podsecuritypolicies
  resourceNames:
    - acm-psp
  verbs:
    - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmanagement.gke.io:monitor
  labels:
    configmanagement.gke.io/system: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmanagement.gke.io:monitor
subjects:
- kind: ServiceAccount
  name: monitor
  namespace: config-management-system
