# Nomos monitor service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor
  namespace: config-management-system
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "legacy"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmanagement.gke.io:monitor
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "legacy"
rules:
- apiGroups:
  - configmanagement.gke.io
  resources:
  - namespaceconfigs
  - clusterconfigs
  - repos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
    - podsecuritypolicies
  resourceNames:
    - acm-psp
  verbs:
    - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmanagement.gke.io:monitor
  labels:
    configmanagement.gke.io/system: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmanagement.gke.io:monitor
subjects:
- kind: ServiceAccount
  name: monitor
  namespace: config-management-system
