# Custom Resource Definition for a NamespaceConfig
# which is a resource containing information about
# a namespace/orgunit, its place in the hierarchy,
# and the policies attached to it.
# See namespace-syncer/pkg/adapater/policy_node.go
# for the CRD struct spec.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: namespaceconfigs.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
spec:
  group: configmanagement.gke.io
  scope: Cluster
  names:
    plural: namespaceconfigs
    singular: namespaceconfig
    kind: NamespaceConfig
    shortNames:
    - nc
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
