# Custom Resource Definition for a Repo
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: repos.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
spec:
  group: configmanagement.gke.io
  version: v1
  scope: Cluster
  names:
    plural: repos
    singular: repo
    kind: Repo
  validation:
    # openAPIV3Schema is the schema for validating custom objects
    # TODO(phillipao): Complete and test when 1.11 beta is out.
    openAPIV3Schema:
      required:
      - spec
      properties:
        spec:
          # RepoSpec
          type: object
          required:
          - version
          properties:
            version:
              type: string
          # /RepoSpec
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
