apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: repos.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "legacy"
spec:
  preserveUnknownFields: false
  group: configmanagement.gke.io
  scope: Cluster
  names:
    plural: repos
    singular: repo
    kind: Repo
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      # openAPIV3Schema is the schema for validating custom objects
      # TODO(phillipao): Complete and test when 1.11 beta is out.
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            # RepoSpec
            type: object
            required:
            - version
            properties:
              version:
                type: string
            # /RepoSpec
          status:
            # RepoStatus
            type: object
            properties:
              source:
                type: object
                properties:
                  token:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        sourcePath:
                          type: string
                        resourceName:
                          type: string
                        resourceNamespace:
                          type: string
                        resourceGVK:
                          type: object
                          properties:
                            Group:
                              type: string
                            Version:
                              type: string
                            Kind:
                              type: string
                        code:
                          type: string
                        errorMessage:
                          type: string
                        errorResources:
                          type: array
                          items:
                            type: object
                            properties:
                              sourcePath:
                                type: string
                                resourceName:
                                  type: string
                                resourceNamespace:
                                  type: string
                                resourceGVK:
                                  type: object
                                  properties:
                                    Group:
                                      type: string
                                    Version:
                                      type: string
                                    Kind:
                                      type: string
              import:
                type: object
                properties:
                  token:
                    type: string
                  lastUpdate: # metav1.Time
                    type: string
                    format: date-time
                    nullable: true
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        sourcePath:
                          type: string
                        resourceName:
                          type: string
                        resourceNamespace:
                          type: string
                        resourceGVK:
                          type: object
                          properties:
                            Group:
                              type: string
                            Version:
                              type: string
                            Kind:
                              type: string
                        code:
                          type: string
                        errorMessage:
                          type: string
                        errorResources:
                          type: array
                          items:
                            type: object
                            properties:
                              sourcePath:
                                type: string
                                resourceName:
                                  type: string
                                resourceNamespace:
                                  type: string
                                resourceGVK:
                                  type: object
                                  properties:
                                    Group:
                                      type: string
                                    Version:
                                      type: string
                                    Kind:
                                      type: string
              sync:
                type: object
                properties:
                  latestToken:
                    type: string
                  lastUpdate: # metav1.Time
                    type: string
                    format: date-time
                    nullable: true
                  inProgress:
                    type: array
                    items:
                      type: object
                      properties:
                        token:
                          type: string
                        errors:
                          type: array
                          items:
                            type: object
                            properties:
                              sourcePath:
                                type: string
                              resourceName:
                                type: string
                              resourceNamespace:
                                type: string
                              resourceGVK:
                                type: object
                                properties:
                                  Group:
                                    type: string
                                  Version:
                                    type: string
                                  Kind:
                                    type: string
                              code:
                                type: string
                              errorMessage:
                                type: string
                              errorResources:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    sourcePath:
                                      type: string
                                      resourceName:
                                        type: string
                                      resourceNamespace:
                                        type: string
                                      resourceGVK:
                                        type: object
                                        properties:
                                          Group:
                                            type: string
                                          Version:
                                            type: string
                                          Kind:
                                            type: string
                  resourceConditions:
                    type: array
                    items:
                      type: object
                      properties:
                        groupVersion:
                          type: string
                        kind:
                          type: string
                        namespacedName:
                          type: string
                        resourceState:
                          type: string
                        token:
                          type: string
                        reconcilingReasons:
                          type: array
                          items:
                            type: string
                        errors:
                          type: array
                          items:
                            type: string
            # /RepoStatus