# Custom Resource Definition for a Repo
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: repos.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
spec:
  group: configmanagement.gke.io
  scope: Cluster
  names:
    plural: repos
    singular: repo
    kind: Repo
  subresources:
    status: {}
  versions:
    - name: v1
      served: true
      storage: true
  validation:
    # openAPIV3Schema is the schema for validating custom objects
    # TODO(phillipao): Complete and test when 1.11 beta is out.
    openAPIV3Schema:
      required:
      - spec
      properties:
        spec:
          # RepoSpec
          type: object
          required:
          - version
          properties:
            version:
              type: string
          # /RepoSpec
        status:
          # RepoStatus
          type: object
          properties:
            source:
              type: object
              properties:
                token:
                  type: string
            import:
              type: object
              properties:
                token:
                  type: string
                lastUpdate: # metav1.Time
                  anyOf:
                  - format: date-time
                    type: string
                  - {}
                errors:
                  type: array
            sync:
              type: object
              properties:
                latestToken:
                  type: string
                lastUpdate: # metav1.Time
                  anyOf:
                  - format: date-time
                    type: string
                  - {}
                inProgress:
                  type: array
          # /RepoStatus
