# Custom Resource Definition for a Repo
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: repos.nomos.dev
  labels:
    nomos.dev/system: "true"
spec:
  group: nomos.dev
  version: v1alpha1
  scope: Cluster
  names:
    plural: repos
    singular: repo
    kind: Repo
  validation:
    # openAPIV3Schema is the schema for validating custom objects
    # TODO(phillipao): Complete and test when 1.11 beta is out.
    openAPIV3Schema:
      # TODO(b/116048028): Add back.
      # required:
      # - spec
      properties:
        spec:
          # RepoSpec
          type: object
          required:
          - version
          properties:
            experimentalHierarchy:
              type: boolean
            version:
              type: string
          # /RepoSpec
