# Custom Resource Definition for a Policy Node
# which is a resource containing information about
# a namespace/orgunit, its place in the hierarchy,
# and the policies attached to it.
# See namespace-syncer/pkg/adapater/policy_node.go
# for the CRD struct spec.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: policynodes.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
spec:
  group: configmanagement.gke.io
  version: v1
  scope: Cluster
  names:
    plural: policynodes
    singular: policynode
    kind: PolicyNode
    shortNames:
    - pn
  subresources:
    status: {}
  validation:
      openAPIV3Schema:
        required:
        - spec
        properties:
          spec:
            # PolicyNodeSpec
            type: object
            properties:
              importToken:
                type: string
              importTime: # metav1.Time
                anyOf:
                - format: date-time
                  type: string
                - {}
              resources:
                type: array
                items:
                  # GenericResources
                  type: object
                  required:
                  - kind
                  - versions
                  properties:
                    group:
                      type: string
                    kind:
                      type: string
                    versions:
                      type: array
                      items:
                        # GenericVersionResources
                        type: object
                        required:
                        - objects
                        - version
                        properties:
                          objects:
                            type: array
                            items:
                              type: object # runtime.RawExtension
                          version:
                            type: string
                        # /GenericVersionResources
                  # /GenericResources
            # /PolicyNodeSpec
          status:
            # PolicyNodeStatus
            type: object
            properties:
              syncTokens:
                type: object # map[string]string
              syncErrors:
                type: array
                items:
                  # PolicyNodeSyncError
                  type: object
                  properties:
                    sourceName:
                      type: string
                    resourceName:
                      type: string
                    resourceKind:
                      type: string
                    resourceAPI:
                      type: string
                    errorMessage:
                      type: string
                  # /PolicyNodeSyncError
              syncTime: # metav1.Time
                anyOf:
                - format: date-time
                  type: string
                - {}
              syncState:
                type: string
                enum:
                - ""
                - "synced"
                - "stale"
                - "error"
            # /PolicyNodeStatus
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
