# Nomos PolicyNodes admission controller service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: policynodes-admission-controller
  namespace: nomos-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nomos-policynodes-admission-controller
rules:
- apiGroups:
  - nomos.dev
  resources:
  - policynodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  verbs:
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  resourceNames:
  - policy-nodes.nomos.dev
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nomos-policynodes-admission-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nomos-policynodes-admission-controller
subjects:
- kind: ServiceAccount
  name: policynodes-admission-controller
  namespace: nomos-system
