# Custom Resource Definition for a Policy Node
# which is a resource containing information about
# a namespace/orgunit, its place in the hierarchy,
# and the policies attached to it.
# See namespace-syncer/pkg/adapater/policy_node.go
# for the CRD struct spec.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: policynodes.nomos.dev
  labels:
    nomos.dev/system: "true"
spec:
  group: nomos.dev
  version: v1
  scope: Cluster
  names:
    plural: policynodes
    singular: policynode
    kind: PolicyNode
    shortNames:
    - pn
