apiVersion: v1
kind: ServiceAccount
metadata:
  name: reconciler-manager
  namespace: config-management-system
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "csmr"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configsync.gke.io:reconciler-manager
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "csmr"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # In order to provision the root reconciler as cluster-admin, the reconciler
  # manager also needs to be cluster-admin. See b/167259858 for more details.
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: reconciler-manager
  namespace: config-management-system
