apiVersion: v1
kind: ServiceAccount
metadata:
  name: reconciler-manager
  namespace: config-management-system
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "csmr"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmanagement.gke.io:reconciler-manager
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "csmr"
rules:
- apiGroups:
  - configmanagement.gke.io
  resources:
  - reposyncs
  verbs:
  - "*"
- apiGroups:
  - configmanagement.gke.io
  resources:
  - reposyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - configmanagement.gke.io
  resources:
  - rootsyncs
  verbs:
  - "*"
- apiGroups:
  - configmanagement.gke.io
  resources:
  - rootsyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmanagement.gke.io:reconciler-manager
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "csmr"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmanagement.gke.io:reconciler-manager
subjects:
- kind: ServiceAccount
  name: reconciler-manager
  namespace: config-management-system
