# Custom Resource Definition for a Stolos Resource Quota which is a resource containing information about
# a resource quota set on a policy space. (Leaf workload namespaces use native ResourceQuota objects).
# See pkg/api/policyhierarchy/v1/types.go for the CRD struct spec.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stolosresourcequota.k8us.k8s.io
spec:
  group: k8us.k8s.io
  version: v1
  scope: Namespace
  names:
    plural: stolosresourcequota
    singular: stolosresourcequota
    kind: StolosResourceQuota
    shortNames:
    - srq
