# Custom Resource Definition for a declaring the types
# of resources Nomos should sync from the source of truth
# See pkg/api/policyhierarchy/v1alpha1/types.go
# for the CRD struct spec.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: syncs.nomos.dev
  labels:
    nomos.dev/system: "true"
spec:
  group: nomos.dev
  version: v1alpha1
  scope: Cluster
  names:
    plural: syncs
    singular: sync
    kind: Sync
