# Custom Resource Definition for a declaring the types
# of resources Nomos should sync from the source of truth
# See pkg/api/policyhierarchy/v1alpha1/types.go
# for the CRD struct spec.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: syncs.nomos.dev
  labels:
    nomos.dev/system: "true"
spec:
  group: nomos.dev
  version: v1alpha1
  scope: Cluster
  names:
    plural: syncs
    singular: sync
    kind: Sync
  validation:
    openAPIV3Schema:
      properties:
        spec:
          # SyncSpec
          type: object
          required:
          - groups
          properties:
            groups:
              type: array
              items:
                # SyncGroup
                type: object
                required:
                - group
                - kinds
                properties:
                  group:
                    type: string
                  kinds:
                    type: array
                    items:
                      # SyncKind
                      type: object
                      required:
                      - kind
                      - versions
                      properties:
                        kind:
                          type: string
                        hierarchyMode:
                          type: string
                          enum:
                          - ""
                          - "hierarchicalQuota"
                          - "inherit"
                          - "none"
                        versions:
                          type: array
                          items:
                            # SyncVersion
                            type: object
                            required:
                            - version
                            properties:
                              version:
                                type: string
                              compareFields:
                                type: array
                                items:
                                  type: string
                            # /SyncVersion
                      # /SyncKind
                # /SyncGroup
          # /SyncSpec
        status:
          # SyncStatus
          type: object
          properties:
            groupVersionKinds:
              type: array
              items:
                # SyncGroupVersionKindStatus
                type: object
                required:
                - group
                - version
                - kind
                - status
                properties:
                  group:
                    type: string
                  version:
                    type: string
                  kind:
                    type: string
                  status:
                    type: string
                    enum:
                    - "syncing"
                    - "error"
                  message:
                    type: string
                # /SyncGroupVersionKindStatus
          # /SyncStatus
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
