# Custom Resource Definition for a declaring the types
# of resources Nomos should sync from the source of truth
# See pkg/api/configmanagement/v1alpha1/types.go
# for the CRD struct spec.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: syncs.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "legacy"
spec:
  preserveUnknownFields: false
  group: configmanagement.gke.io
  scope: Cluster
  names:
    plural: syncs
    singular: sync
    kind: Sync
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
          - spec
          properties:
            spec:
              # SyncSpec
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              # SyncStatus
              type: object
              x-kubernetes-preserve-unknown-fields: true