# Custom Resource Definition for a declaring the types
# of resources Nomos should sync from the source of truth
# See pkg/api/configmanagement/v1alpha1/types.go
# for the CRD struct spec.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: syncs.configmanagement.gke.io
  labels:
    configmanagement.gke.io/system: "true"
spec:
  group: configmanagement.gke.io
  version: v1
  scope: Cluster
  names:
    plural: syncs
    singular: sync
    kind: Sync
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required:
      - spec
      properties:
        spec:
          # SyncSpec
          type: object
          #required:
          #- groups
          #properties:
          #  groups:
          #    type: array
          #    items:
          #      # SyncGroup
          #      type: object
          #      required:
          #      - group
          #      - kinds
          #      properties:
          #        group:
          #          type: string
          #        kinds:
          #          type: array
          #          items:
          #            # SyncKind
          #            type: object
          #            required:
          #            - kind
          #            properties:
          #              kind:
          #                type: string
                      # /SyncKind
                # /SyncGroup
          # /SyncSpec
        status:
          # SyncStatus
          type: object
          #properties:
          #  groupVersionKinds:
          #    type: array
          #    items:
          #      # SyncGroupVersionKindStatus
          #      type: object
          #      required:
          #      - group
          #      - version
          #      - kind
          #      - status
          #      properties:
          #        group:
          #          type: string
          #        version:
          #          type: string
          #        kind:
          #          type: string
          #        status:
          #          type: string
          #          enum:
          #          - "syncing"
          #          - "error"
          #        message:
          #          type: string
                # /SyncGroupVersionKindStatus
          # /SyncStatus
