/*
Copyright 2018 The Nomos Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	policyascode_v1 "github.com/google/nomos/pkg/api/policyascode/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOrganizations implements OrganizationInterface
type FakeOrganizations struct {
	Fake *FakeBespinV1
}

var organizationsResource = schema.GroupVersionResource{Group: "bespin.dev", Version: "v1", Resource: "organizations"}

var organizationsKind = schema.GroupVersionKind{Group: "bespin.dev", Version: "v1", Kind: "Organization"}

// Get takes name of the organization, and returns the corresponding organization object, and an error if there is any.
func (c *FakeOrganizations) Get(name string, options v1.GetOptions) (result *policyascode_v1.Organization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(organizationsResource, name), &policyascode_v1.Organization{})
	if obj == nil {
		return nil, err
	}
	return obj.(*policyascode_v1.Organization), err
}

// List takes label and field selectors, and returns the list of Organizations that match those selectors.
func (c *FakeOrganizations) List(opts v1.ListOptions) (result *policyascode_v1.OrganizationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(organizationsResource, organizationsKind, opts), &policyascode_v1.OrganizationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &policyascode_v1.OrganizationList{ListMeta: obj.(*policyascode_v1.OrganizationList).ListMeta}
	for _, item := range obj.(*policyascode_v1.OrganizationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested organizations.
func (c *FakeOrganizations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(organizationsResource, opts))
}

// Create takes the representation of a organization and creates it.  Returns the server's representation of the organization, and an error, if there is any.
func (c *FakeOrganizations) Create(organization *policyascode_v1.Organization) (result *policyascode_v1.Organization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(organizationsResource, organization), &policyascode_v1.Organization{})
	if obj == nil {
		return nil, err
	}
	return obj.(*policyascode_v1.Organization), err
}

// Update takes the representation of a organization and updates it. Returns the server's representation of the organization, and an error, if there is any.
func (c *FakeOrganizations) Update(organization *policyascode_v1.Organization) (result *policyascode_v1.Organization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(organizationsResource, organization), &policyascode_v1.Organization{})
	if obj == nil {
		return nil, err
	}
	return obj.(*policyascode_v1.Organization), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOrganizations) UpdateStatus(organization *policyascode_v1.Organization) (*policyascode_v1.Organization, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(organizationsResource, "status", organization), &policyascode_v1.Organization{})
	if obj == nil {
		return nil, err
	}
	return obj.(*policyascode_v1.Organization), err
}

// Delete takes name of the organization and deletes it. Returns an error if one occurs.
func (c *FakeOrganizations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(organizationsResource, name), &policyascode_v1.Organization{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOrganizations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(organizationsResource, listOptions)

	_, err := c.Fake.Invokes(action, &policyascode_v1.OrganizationList{})
	return err
}

// Patch applies the patch and returns the patched organization.
func (c *FakeOrganizations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *policyascode_v1.Organization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(organizationsResource, name, data, subresources...), &policyascode_v1.Organization{})
	if obj == nil {
		return nil, err
	}
	return obj.(*policyascode_v1.Organization), err
}
