/*
Copyright 2019 The Nomos Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "github.com/google/nomos/clientgen/apis/scheme"
	v1 "github.com/google/nomos/pkg/api/policyascode/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterOrganizationPoliciesGetter has a method to return a ClusterOrganizationPolicyInterface.
// A group's client should implement this interface.
type ClusterOrganizationPoliciesGetter interface {
	ClusterOrganizationPolicies() ClusterOrganizationPolicyInterface
}

// ClusterOrganizationPolicyInterface has methods to work with ClusterOrganizationPolicy resources.
type ClusterOrganizationPolicyInterface interface {
	Create(*v1.ClusterOrganizationPolicy) (*v1.ClusterOrganizationPolicy, error)
	Update(*v1.ClusterOrganizationPolicy) (*v1.ClusterOrganizationPolicy, error)
	UpdateStatus(*v1.ClusterOrganizationPolicy) (*v1.ClusterOrganizationPolicy, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.ClusterOrganizationPolicy, error)
	List(opts meta_v1.ListOptions) (*v1.ClusterOrganizationPolicyList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ClusterOrganizationPolicy, err error)
	ClusterOrganizationPolicyExpansion
}

// clusterOrganizationPolicies implements ClusterOrganizationPolicyInterface
type clusterOrganizationPolicies struct {
	client rest.Interface
}

// newClusterOrganizationPolicies returns a ClusterOrganizationPolicies
func newClusterOrganizationPolicies(c *BespinV1Client) *clusterOrganizationPolicies {
	return &clusterOrganizationPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterOrganizationPolicy, and returns the corresponding clusterOrganizationPolicy object, and an error if there is any.
func (c *clusterOrganizationPolicies) Get(name string, options meta_v1.GetOptions) (result *v1.ClusterOrganizationPolicy, err error) {
	result = &v1.ClusterOrganizationPolicy{}
	err = c.client.Get().
		Resource("clusterorganizationpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterOrganizationPolicies that match those selectors.
func (c *clusterOrganizationPolicies) List(opts meta_v1.ListOptions) (result *v1.ClusterOrganizationPolicyList, err error) {
	result = &v1.ClusterOrganizationPolicyList{}
	err = c.client.Get().
		Resource("clusterorganizationpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterOrganizationPolicies.
func (c *clusterOrganizationPolicies) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("clusterorganizationpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a clusterOrganizationPolicy and creates it.  Returns the server's representation of the clusterOrganizationPolicy, and an error, if there is any.
func (c *clusterOrganizationPolicies) Create(clusterOrganizationPolicy *v1.ClusterOrganizationPolicy) (result *v1.ClusterOrganizationPolicy, err error) {
	result = &v1.ClusterOrganizationPolicy{}
	err = c.client.Post().
		Resource("clusterorganizationpolicies").
		Body(clusterOrganizationPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterOrganizationPolicy and updates it. Returns the server's representation of the clusterOrganizationPolicy, and an error, if there is any.
func (c *clusterOrganizationPolicies) Update(clusterOrganizationPolicy *v1.ClusterOrganizationPolicy) (result *v1.ClusterOrganizationPolicy, err error) {
	result = &v1.ClusterOrganizationPolicy{}
	err = c.client.Put().
		Resource("clusterorganizationpolicies").
		Name(clusterOrganizationPolicy.Name).
		Body(clusterOrganizationPolicy).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *clusterOrganizationPolicies) UpdateStatus(clusterOrganizationPolicy *v1.ClusterOrganizationPolicy) (result *v1.ClusterOrganizationPolicy, err error) {
	result = &v1.ClusterOrganizationPolicy{}
	err = c.client.Put().
		Resource("clusterorganizationpolicies").
		Name(clusterOrganizationPolicy.Name).
		SubResource("status").
		Body(clusterOrganizationPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterOrganizationPolicy and deletes it. Returns an error if one occurs.
func (c *clusterOrganizationPolicies) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterorganizationpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterOrganizationPolicies) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Resource("clusterorganizationpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterOrganizationPolicy.
func (c *clusterOrganizationPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ClusterOrganizationPolicy, err error) {
	result = &v1.ClusterOrganizationPolicy{}
	err = c.client.Patch(pt).
		Resource("clusterorganizationpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
