kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: repoless-admin
  labels:
    testdata: "true"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list"]
