apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syncer-service-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - resourcequotas
  verbs:
  - '*'
- apiGroups:
  - k8us.k8s.io
  resources:
  - policynodes
  verbs:
  - get
  - list
  - watch