apiVersion: "nomos.dev/v1"
kind: PolicyNode
metadata:
  name: backend
spec:
  policyspace: false
  parent: eng
  policies:
    resourceQuotaV1:
      hard:
        pods: "1"
    rolebindingsV1:
    - kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        namespace: backend
        name: robert-rolebinding
      subjects:
      - kind: User
        name: robert@acme.com
        apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: Role
        name: acme-admin
        apiGroup: rbac.authorization.k8s.io
