contexts:
  - kubeconfig_context_of_your_cluster
git:
  GIT_SYNC_BRANCH: master
  GIT_SYNC_REPO: git@github.com:frankfarzan/foo-corp-example.git
  GIT_SYNC_WAIT: 60
  ROOT_POLICY_DIR: foo-corp
ssh:
  knownHostsFilename: $HOME/.ssh/id_rsa.edit_this_filename
  privateKeyFilename: $HOME/.ssh/known_hosts.edit_this_filename
user: youruser@example.com

