apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    bespin.dev/system: "true"
  name: projects.bespin.dev
spec:
  group: bespin.dev
  names:
    kind: Project
    plural: projects
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            displayName:
              pattern: '[a-zA-Z][\w!"\- ]{3,27}'
              type: string
            id:
              pattern: ^[a-z][a-z\d\-]{5,29}$
              type: string
            parentRef:
              type: object
          required:
          - displayName
          - id
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
          type: object
      required:
      - spec
      type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
