apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    bespin.dev/system: "true"
  name: clusteriampolicies.bespin.dev
spec:
  group: bespin.dev
  names:
    kind: ClusterIAMPolicy
    plural: clusteriampolicies
  scope: Cluster
  # TODO(b/118383540): This is commented out because a bug in GKE 1.10 Alpha is rejecting
  # the validation schema even though it is valid.
  # validation:
  #   openAPIV3Schema:
  #     properties:
  #       apiVersion:
  #         type: string
  #       kind:
  #         type: string
  #       metadata:
  #         type: object
  #       spec:
  #         properties:
  #           bindings:
  #             items:
  #               properties:
  #                 members:
  #                   items:
  #                     pattern: ^(user|serviceAccount|group|domain):.+$
  #                     type: string
  #                   pattern: ^(user|serviceAccount|group|domain):.+$
  #                   type: array
  #                 role:
  #                   pattern: ^roles/[\w\.]+$
  #                   type: string
  #               required:
  #               - members
  #               - role
  #               type: object
  #             type: array
  #           importDetails:
  #             properties:
  #               time:
  #                 format: date-time
  #                 type: string
  #               token:
  #                 pattern: ^\w{40}$
  #                 type: string
  #             required:
  #             - token
  #             - time
  #             type: object
  #           resourceReference:
  #             properties:
  #               kind:
  #                 pattern: ^(Organization|Folder|Project)$
  #                 type: string
  #               name:
  #                 type: string
  #             required:
  #             - kind
  #             - name
  #             type: object
  #         required:
  #         - resourceReference
  #         - bindings
  #         - importDetails
  #         type: object
  #       status:
  #         properties:
  #           syncDetails:
  #             properties:
  #               error:
  #                 type: string
  #               time:
  #                 format: date-time
  #                 type: string
  #               token:
  #                 pattern: ^\w{40}$
  #                 type: string
  #             type: object
  #         type: object
  #     type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
