apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    bespin.dev/system: "true"
  name: clusteriampolicies.bespin.dev
spec:
  group: bespin.dev
  names:
    kind: ClusterIAMPolicy
    plural: clusteriampolicies
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            bindings:
              items:
                properties:
                  members:
                    items:
                      pattern: ^(user|serviceAccount|group|domain):.+$
                      type: string
                    pattern: ^(user|serviceAccount|group|domain):.+$
                    type: array
                  role:
                    pattern: ^roles/[\w\.]+$
                    type: string
                required:
                - members
                - role
                type: object
              type: array
            resourceRef:
              type: object
          required:
          - resourceRef
          - bindings
          - importDetails
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
          type: object
      type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
