apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    bespin.dev/system: "true"
  name: clusterorganizationpolicies.bespin.dev
spec:
  group: bespin.dev
  names:
    kind: ClusterOrganizationPolicy
    plural: clusterorganizationpolicies
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            constraints:
              items:
                properties:
                  booleanPolicy:
                    properties:
                      enforced:
                        type: boolean
                    required:
                    - enforced
                    type: object
                  constraint:
                    type: string
                  listPolicy:
                    properties:
                      allValues:
                        pattern: ^(ALLOW|DENY)$
                        type: string
                      allowedValues:
                        items:
                          pattern: ^((is|under):)?(organizations|folders|projects)/
                          type: string
                        pattern: ^((is|under):)?(organizations|folders|projects)/
                        type: array
                      disallowedValues:
                        items:
                          pattern: ^((is|under):)?(organizations|folders|projects)/
                          type: string
                        pattern: ^((is|under):)?(organizations|folders|projects)/
                        type: array
                      inheritFromParent:
                        type: boolean
                    type: object
                required:
                - constraint
                type: object
              type: array
            resourceRef:
              type: object
          required:
          - constraints
          - resourceRef
          - importDetails
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
          type: object
      type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
