apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    bespin.dev/system: "true"
  name: iampolicies.bespin.dev
spec:
  group: bespin.dev
  names:
    kind: IAMPolicy
    plural: iampolicies
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            bindings:
              items:
                properties:
                  members:
                    items:
                      pattern: ^((user|serviceAccount|group|domain):.+)|allAuthenticatedUsers|allUsers$
                      type: string
                    pattern: ^((user|serviceAccount|group|domain):.+)|allAuthenticatedUsers|allUsers$
                    type: array
                  role:
                    pattern: (^roles|^(projects|organizations)/.+/roles)/[\w\.]+$
                    type: string
                required:
                - members
                - role
                type: object
              type: array
            resourceRef:
              type: object
          required:
          - resourceRef
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
          type: object
      required:
      - spec
      type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
