apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    bespin.dev/system: "true"
  name: folders.bespin.dev
spec:
  group: bespin.dev
  names:
    kind: Folder
    plural: folders
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            displayName:
              pattern: '[a-zA-Z\d][\w_ \-]{3,27}[\w\d]?'
              type: string
            id:
              format: int64
              minimum: 1
              type: integer
            parentRef:
              type: object
          required:
          - displayName
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
          type: object
      required:
      - spec
      type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
