name: "nomos"
shortDesc: "Nomos Stuff"
longDesc: "Nomos is a thing that manages other things and also prints this message."
example: "nomos nope nope nope"
command: "./kubectl-nomos"
flags:
  - name: "demo"
    shorthand: "d"
    desc: "This is a demo flag with empty default value"
    defValue: ""
  - name: "yep"
    shorthand: "o" # n, s, v are taken =(
    desc: "This is a demo flag with a default value"
    defValue: "nope"
tree:
  - name: "get"
    shortDesc: "get nomos things"
    longDesc: "Nomos is a thing that manages other things and also prints this message."
    example: "nomos nope nope nope"
    command: "./kubectl-nomos get"
    tree:
      - name: "rolebindings"
        shortDesc: "get nomos things"
        longDesc: "Nomos is a thing that manages other things and also prints this message."
        example: "nomos nope nope nope"
        command: "./kubectl-nomos get rolebindings"
