apiVersion: addons.sigs.k8s.io/v1alpha1
kind: Nomos
metadata:
  name: nomos
spec:
  git:
    syncRepo: git@github.com:frankfarzan/foo-corp-example.git
    syncBranch: dev
    syncWait: 1
    secretType: ssh
    policyDir: foo-corp
  channel: dev
