kind: ClusterSelector
apiVersion: configmanagement.gke.io/v1
metadata:
  name: cluster-selector-prod
spec:
  selector:
    matchExpressions:
      - key: environment
        operator: In
        values:
          - prod
