// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	scheme "github.com/google/nomos/clientgen/apis/scheme"
	v1 "github.com/google/nomos/pkg/api/configmanagement/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterSelectorsGetter has a method to return a ClusterSelectorInterface.
// A group's client should implement this interface.
type ClusterSelectorsGetter interface {
	ClusterSelectors() ClusterSelectorInterface
}

// ClusterSelectorInterface has methods to work with ClusterSelector resources.
type ClusterSelectorInterface interface {
	Create(*v1.ClusterSelector) (*v1.ClusterSelector, error)
	Update(*v1.ClusterSelector) (*v1.ClusterSelector, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ClusterSelector, error)
	List(opts metav1.ListOptions) (*v1.ClusterSelectorList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ClusterSelector, err error)
	ClusterSelectorExpansion
}

// clusterSelectors implements ClusterSelectorInterface
type clusterSelectors struct {
	client rest.Interface
}

// newClusterSelectors returns a ClusterSelectors
func newClusterSelectors(c *ConfigmanagementV1Client) *clusterSelectors {
	return &clusterSelectors{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterSelector, and returns the corresponding clusterSelector object, and an error if there is any.
func (c *clusterSelectors) Get(name string, options metav1.GetOptions) (result *v1.ClusterSelector, err error) {
	result = &v1.ClusterSelector{}
	err = c.client.Get().
		Resource("clusterselectors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterSelectors that match those selectors.
func (c *clusterSelectors) List(opts metav1.ListOptions) (result *v1.ClusterSelectorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ClusterSelectorList{}
	err = c.client.Get().
		Resource("clusterselectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterSelectors.
func (c *clusterSelectors) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clusterselectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a clusterSelector and creates it.  Returns the server's representation of the clusterSelector, and an error, if there is any.
func (c *clusterSelectors) Create(clusterSelector *v1.ClusterSelector) (result *v1.ClusterSelector, err error) {
	result = &v1.ClusterSelector{}
	err = c.client.Post().
		Resource("clusterselectors").
		Body(clusterSelector).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterSelector and updates it. Returns the server's representation of the clusterSelector, and an error, if there is any.
func (c *clusterSelectors) Update(clusterSelector *v1.ClusterSelector) (result *v1.ClusterSelector, err error) {
	result = &v1.ClusterSelector{}
	err = c.client.Put().
		Resource("clusterselectors").
		Name(clusterSelector.Name).
		Body(clusterSelector).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterSelector and deletes it. Returns an error if one occurs.
func (c *clusterSelectors) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterselectors").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterSelectors) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clusterselectors").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterSelector.
func (c *clusterSelectors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ClusterSelector, err error) {
	result = &v1.ClusterSelector{}
	err = c.client.Patch(pt).
		Resource("clusterselectors").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
