#!/bin/bash

source $(dirname $0)/gce-common.sh

KUBERNETES_RELEASE="v1.9.2"
KUBERNETES_SKIP_CONFIRM=1
KUBERNETES_SKIP_CREATE_CLUSTER=1

cd ${STOLOS_TMP}
export KUBERNETES_RELEASE KUBERNETES_SKIP_CONFIRM KUBERNETES_SKIP_CREATE_CLUSTER
curl -sS https://get.k8s.io | bash
