/*
Copyright 2019 The CSP Config Management Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	configmanagement_v1 "github.com/google/nomos/pkg/api/configmanagement/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNamespaceConfigs implements NamespaceConfigInterface
type FakeNamespaceConfigs struct {
	Fake *FakeConfigmanagementV1
}

var namespaceconfigsResource = schema.GroupVersionResource{Group: "configmanagement.gke.io", Version: "v1", Resource: "namespaceconfigs"}

var namespaceconfigsKind = schema.GroupVersionKind{Group: "configmanagement.gke.io", Version: "v1", Kind: "NamespaceConfig"}

// Get takes name of the namespaceConfig, and returns the corresponding namespaceConfig object, and an error if there is any.
func (c *FakeNamespaceConfigs) Get(name string, options v1.GetOptions) (result *configmanagement_v1.NamespaceConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(namespaceconfigsResource, name), &configmanagement_v1.NamespaceConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagement_v1.NamespaceConfig), err
}

// List takes label and field selectors, and returns the list of NamespaceConfigs that match those selectors.
func (c *FakeNamespaceConfigs) List(opts v1.ListOptions) (result *configmanagement_v1.NamespaceConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(namespaceconfigsResource, namespaceconfigsKind, opts), &configmanagement_v1.NamespaceConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &configmanagement_v1.NamespaceConfigList{ListMeta: obj.(*configmanagement_v1.NamespaceConfigList).ListMeta}
	for _, item := range obj.(*configmanagement_v1.NamespaceConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested namespaceConfigs.
func (c *FakeNamespaceConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(namespaceconfigsResource, opts))
}

// Create takes the representation of a namespaceConfig and creates it.  Returns the server's representation of the namespaceConfig, and an error, if there is any.
func (c *FakeNamespaceConfigs) Create(namespaceConfig *configmanagement_v1.NamespaceConfig) (result *configmanagement_v1.NamespaceConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(namespaceconfigsResource, namespaceConfig), &configmanagement_v1.NamespaceConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagement_v1.NamespaceConfig), err
}

// Update takes the representation of a namespaceConfig and updates it. Returns the server's representation of the namespaceConfig, and an error, if there is any.
func (c *FakeNamespaceConfigs) Update(namespaceConfig *configmanagement_v1.NamespaceConfig) (result *configmanagement_v1.NamespaceConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(namespaceconfigsResource, namespaceConfig), &configmanagement_v1.NamespaceConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagement_v1.NamespaceConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNamespaceConfigs) UpdateStatus(namespaceConfig *configmanagement_v1.NamespaceConfig) (*configmanagement_v1.NamespaceConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(namespaceconfigsResource, "status", namespaceConfig), &configmanagement_v1.NamespaceConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagement_v1.NamespaceConfig), err
}

// Delete takes name of the namespaceConfig and deletes it. Returns an error if one occurs.
func (c *FakeNamespaceConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(namespaceconfigsResource, name), &configmanagement_v1.NamespaceConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNamespaceConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(namespaceconfigsResource, listOptions)

	_, err := c.Fake.Invokes(action, &configmanagement_v1.NamespaceConfigList{})
	return err
}

// Patch applies the patch and returns the patched namespaceConfig.
func (c *FakeNamespaceConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *configmanagement_v1.NamespaceConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(namespaceconfigsResource, name, data, subresources...), &configmanagement_v1.NamespaceConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*configmanagement_v1.NamespaceConfig), err
}
