apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nomos
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      monitored: "true"
  namespaceSelector:
    matchNames:
    - nomos-system
  endpoints:
  - port: metrics
    interval: 10s