# Stolos StolosResourceQuota controller service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stolosresourcequota-controller
  namespace: stolos-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stolos-stolosresourcequota-controller
rules:
- apiGroups:
  - stolos.dev
  resources:
  - policynodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stolos.dev
  resources:
  - stolosresourcequotas
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  - resourcequotas
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stolos-stolosresourcequota-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stolos-stolosresourcequota-controller
subjects:
- kind: ServiceAccount
  name: stolosresourcequota-controller
  namespace: stolos-system
