# Resources in this file are only for development purposes and should not be
# included in the shipped configsync multi repo.
# TODO b/159065780 Remove once integrated with Operator actuation, since
# operator will create the namespace config-management-system.
apiVersion: v1
kind: Namespace
metadata:
  name: bookinfo
