apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyproxy-deployment
  namespace: config-management-system
spec:
  selector:
    matchLabels:
      app: tinyproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: tinyproxy
    spec:
      containers:
      - name: tinyproxy
        image: travix/tinyproxy
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: tinyproxy-service
  namespace: config-management-system
spec:
  selector:
    app: tinyproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888

