apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: backend
spec:
  containers:
  - name: demo
    image: us.gcr.io/mdruskin-gketest1/demo:test
    ports:
    - containerPort: 80
    imagePullPolicy: Always
