apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-compute-quota
  annotations:
      configmanagement.gke.io/cluster-selector: selector-env-test
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi