kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stable-devs
  annotations:
      configmanagement.gke.io/cluster-selector: selector-env-dev
subjects:
- kind: Group
  name: system:serviceaccounts:audit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
