kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sre-admin
  annotations:
    nomos.dev/namespace-selector: sre-supported
subjects:
- kind: Group
  name: sre@acme.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: acme-admin
  apiGroup: rbac.authorization.k8s.io