apiVersion: v1
kind: Pod
metadata:
  name: syncer
  namespace: stolos-system
spec:
  automountServiceAccountToken: true
  serviceAccountName: stolos-service
  containers:
  - name: syncer
    image: IMAGE_NAME
    ports:
    - containerPort: 80
    imagePullPolicy: Always
