kind: Sync
apiVersion: nomos.dev/v1alpha1
metadata:
  name: rbac-sync
spec:
  groups:
  - group: rbac.authorization.k8s.io
    kinds:
    - kind: ClusterRole
      versions:
      - version: v1
    - kind: Role
      versions:
      - version: v1
    - kind: RoleBinding
      versions:
      - version: v1
