apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhook
  namespace: config-management-system
  labels:
    app: admission-webhook
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "csmr"
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: admission-webhook
  replicas: 2
  template:
    metadata:
      labels:
        app: admission-webhook
    spec:
      serviceAccountName: admission-webhook
      containers:
      - command:
        - /admission-webhook
        image: IMAGE_NAME
        name: admission-webhook
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 200m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
