# TODO(b/158594746): Use one git-importer deployment instead of three.
apiVersion: v1
kind: Service
metadata:
  name: git-importer
  namespace: config-management-system
  labels:
    monitored: "true"
    configmanagement.gke.io/system: "true"
spec:
  selector:
    app: git-importer
  ports:
    - name: metrics
      port: 8675
      targetPort: metrics-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-importer
  namespace: config-management-system
  labels:
    app: git-importer
    configmanagement.gke.io/system: "true"
spec:
  minReadySeconds: 10
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: git-importer
  template:
    metadata:
      labels:
        app: git-importer
    spec:
      serviceAccountName: importer
      containers:
      - name: importer
        image: IMAGE_NAME
        command: ["git-importer"]
        args:
        - "--v=0"
        ports:
          - containerPort: 8675
            name: metrics-port
        volumeMounts:
          - name: repo
            mountPath: /repo
            readOnly: true
        envFrom:
          - configMapRef:
              name: importer
          - configMapRef:
              name: cluster-name
              optional: true  # If cluster naming is not used, this config map will be missing.
          - configMapRef:
              name: source-format
              optional: true
        resources:
          requests:
            cpu: "150m"
            memory: "100Mi"
          limits:
            cpu: "1"
            memory: "200Mi"
      - name: fs-watcher
        image: IMAGE_NAME
        command: ["git-importer"]
        args:
        - "--v=0"
        - "--watch-directory=/repo"
        volumeMounts:
          - name: repo
            mountPath: /repo
            readOnly: true
        envFrom:
          - configMapRef:
              name: importer-fs-watcher # allow user override for WATCH_PERIOD
              optional: true
        resources:
          requests:
            cpu: "150m"
            memory: "100Mi"
          limits:
            cpu: "1"
            memory: "200Mi"
      - name: git-sync
        image: gcr.io/config-management-release/git-sync:v3.1.6-gke.0__linux_amd64
        # Do not put "rev-" in the root arg or you will break our parsing of commit hashes. See
        # pkg/policyimporter/git/git.go to see where we depend on that magic string from git-sync.
        args: ["--root=/repo", "--dest=rev", "--max-sync-failures=30", "--v=5"]
        volumeMounts:
        - name: repo
          mountPath: /repo
        - name: git-creds
          mountPath: /etc/git-secret
          readOnly: true
        securityContext:
          runAsUser: 65533 # this is a non-root user declared by git-sync
        envFrom:
          - configMapRef:
              name: git-sync
      volumes:
      - name: repo
      - name: git-creds
        secret:
          secretName: git-creds
          defaultMode: 288 # 0440; we need group read so that fsGroup below gives access
      securityContext:
        fsGroup: 65533 # to make SSH key readable
