changecom(`<unused>')
apiVersion: v1
kind: Service
metadata:
  name: syncer
  namespace: nomos-system
  labels:
    monitored: "true"
spec:
  selector:
    app: syncer
  ports:
  - name: metrics
    port: 8675
    targetPort: metrics-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncer
  namespace: nomos-system
  labels:
    app: syncer
spec:
  minReadySeconds: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: syncer
  template:
    metadata:
      labels:
        app: syncer
    spec:
      serviceAccountName: syncer
      containers:
      - name: syncer
        image: IMAGE_NAME
        command: ["syncer"]
        args:
        - "--v=2"
        ports:
        - containerPort: 8675
          name: metrics-port
        env:
        - name: GCP_MODE
          valueFrom:
            configMapKeyRef:
              name: syncer
              key: gcp.mode
