/*
Copyright 2019 The Nomos Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "github.com/google/nomos/clientgen/apis/scheme"
	v1 "github.com/google/nomos/pkg/api/policyhierarchy/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HierarchyConfigsGetter has a method to return a HierarchyConfigInterface.
// A group's client should implement this interface.
type HierarchyConfigsGetter interface {
	HierarchyConfigs() HierarchyConfigInterface
}

// HierarchyConfigInterface has methods to work with HierarchyConfig resources.
type HierarchyConfigInterface interface {
	Create(*v1.HierarchyConfig) (*v1.HierarchyConfig, error)
	Update(*v1.HierarchyConfig) (*v1.HierarchyConfig, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.HierarchyConfig, error)
	List(opts meta_v1.ListOptions) (*v1.HierarchyConfigList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.HierarchyConfig, err error)
	HierarchyConfigExpansion
}

// hierarchyConfigs implements HierarchyConfigInterface
type hierarchyConfigs struct {
	client rest.Interface
}

// newHierarchyConfigs returns a HierarchyConfigs
func newHierarchyConfigs(c *ConfigmanagementV1Client) *hierarchyConfigs {
	return &hierarchyConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the hierarchyConfig, and returns the corresponding hierarchyConfig object, and an error if there is any.
func (c *hierarchyConfigs) Get(name string, options meta_v1.GetOptions) (result *v1.HierarchyConfig, err error) {
	result = &v1.HierarchyConfig{}
	err = c.client.Get().
		Resource("hierarchyconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HierarchyConfigs that match those selectors.
func (c *hierarchyConfigs) List(opts meta_v1.ListOptions) (result *v1.HierarchyConfigList, err error) {
	result = &v1.HierarchyConfigList{}
	err = c.client.Get().
		Resource("hierarchyconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hierarchyConfigs.
func (c *hierarchyConfigs) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("hierarchyconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a hierarchyConfig and creates it.  Returns the server's representation of the hierarchyConfig, and an error, if there is any.
func (c *hierarchyConfigs) Create(hierarchyConfig *v1.HierarchyConfig) (result *v1.HierarchyConfig, err error) {
	result = &v1.HierarchyConfig{}
	err = c.client.Post().
		Resource("hierarchyconfigs").
		Body(hierarchyConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hierarchyConfig and updates it. Returns the server's representation of the hierarchyConfig, and an error, if there is any.
func (c *hierarchyConfigs) Update(hierarchyConfig *v1.HierarchyConfig) (result *v1.HierarchyConfig, err error) {
	result = &v1.HierarchyConfig{}
	err = c.client.Put().
		Resource("hierarchyconfigs").
		Name(hierarchyConfig.Name).
		Body(hierarchyConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the hierarchyConfig and deletes it. Returns an error if one occurs.
func (c *hierarchyConfigs) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("hierarchyconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hierarchyConfigs) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Resource("hierarchyconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hierarchyConfig.
func (c *hierarchyConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.HierarchyConfig, err error) {
	result = &v1.HierarchyConfig{}
	err = c.client.Patch(pt).
		Resource("hierarchyconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
