/*
Copyright 2019 The Nomos Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"github.com/google/nomos/clientgen/apis/scheme"
	v1 "github.com/google/nomos/pkg/api/policyhierarchy/v1"
	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
)

type ConfigmanagementV1Interface interface {
	RESTClient() rest.Interface
	ClusterConfigsGetter
	ClusterSelectorsGetter
	HierarchicalQuotasGetter
	HierarchyConfigsGetter
	NamespaceConfigsGetter
	NamespaceSelectorsGetter
	SyncsGetter
}

// ConfigmanagementV1Client is used to interact with features provided by the configmanagement.gke.io group.
type ConfigmanagementV1Client struct {
	restClient rest.Interface
}

func (c *ConfigmanagementV1Client) ClusterConfigs() ClusterConfigInterface {
	return newClusterConfigs(c)
}

func (c *ConfigmanagementV1Client) ClusterSelectors() ClusterSelectorInterface {
	return newClusterSelectors(c)
}

func (c *ConfigmanagementV1Client) HierarchicalQuotas() HierarchicalQuotaInterface {
	return newHierarchicalQuotas(c)
}

func (c *ConfigmanagementV1Client) HierarchyConfigs() HierarchyConfigInterface {
	return newHierarchyConfigs(c)
}

func (c *ConfigmanagementV1Client) NamespaceConfigs() NamespaceConfigInterface {
	return newNamespaceConfigs(c)
}

func (c *ConfigmanagementV1Client) NamespaceSelectors() NamespaceSelectorInterface {
	return newNamespaceSelectors(c)
}

func (c *ConfigmanagementV1Client) Syncs() SyncInterface {
	return newSyncs(c)
}

// NewForConfig creates a new ConfigmanagementV1Client for the given config.
func NewForConfig(c *rest.Config) (*ConfigmanagementV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &ConfigmanagementV1Client{client}, nil
}

// NewForConfigOrDie creates a new ConfigmanagementV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ConfigmanagementV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ConfigmanagementV1Client for the given RESTClient.
func New(c rest.Interface) *ConfigmanagementV1Client {
	return &ConfigmanagementV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ConfigmanagementV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
