# This is meant to be a sane, default configuration with which the nomos components can be
# installed for e2e testing.  The assumption is that an individual test will override these
# configMaps and restart their associated pods.

# First off, we need to deploy a set of configMaps to replace those that the operator would
# normally deploy for us.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-name
  namespace: config-management-system
data:
  CLUSTER_NAME: e2e-test-cluster
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: git-sync
  namespace: config-management-system
data:
  GIT_KNOWN_HOSTS: "false"
  GIT_SYNC_BRANCH: main
  GIT_SYNC_REPO: GIT_REPO_URL
  GIT_SYNC_REV: HEAD
  GIT_SYNC_WAIT: "1"
  GIT_SYNC_SSH: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: importer
  namespace: config-management-system
data:
  POLICY_DIR: acme
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: source-format
  namespace: config-management-system
data:
  SOURCE_FORMAT: ""
