/*
Copyright 2018 The Nomos Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo.
// source: github.com/google/nomos/pkg/api/policyhierarchy/v1/generated.proto
// DO NOT EDIT!

/*
	Package v1 is a generated protocol buffer package.

	It is generated from these files:
		github.com/google/nomos/pkg/api/policyhierarchy/v1/generated.proto

	It has these top-level messages:
		ClusterPolicies
		ClusterPolicy
		ClusterPolicyList
		ClusterPolicySpec
		Policies
		PolicyNode
		PolicyNodeList
		PolicyNodeSpec
*/
package v1

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import k8s_io_api_core_v1 "k8s.io/api/core/v1"
import k8s_io_api_extensions_v1beta1 "k8s.io/api/extensions/v1beta1"
import k8s_io_api_rbac_v1 "k8s.io/api/rbac/v1"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func (m *ClusterPolicies) Reset()                    { *m = ClusterPolicies{} }
func (*ClusterPolicies) ProtoMessage()               {}
func (*ClusterPolicies) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{0} }

func (m *ClusterPolicy) Reset()                    { *m = ClusterPolicy{} }
func (*ClusterPolicy) ProtoMessage()               {}
func (*ClusterPolicy) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{1} }

func (m *ClusterPolicyList) Reset()                    { *m = ClusterPolicyList{} }
func (*ClusterPolicyList) ProtoMessage()               {}
func (*ClusterPolicyList) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{2} }

func (m *ClusterPolicySpec) Reset()                    { *m = ClusterPolicySpec{} }
func (*ClusterPolicySpec) ProtoMessage()               {}
func (*ClusterPolicySpec) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{3} }

func (m *Policies) Reset()                    { *m = Policies{} }
func (*Policies) ProtoMessage()               {}
func (*Policies) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{4} }

func (m *PolicyNode) Reset()                    { *m = PolicyNode{} }
func (*PolicyNode) ProtoMessage()               {}
func (*PolicyNode) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{5} }

func (m *PolicyNodeList) Reset()                    { *m = PolicyNodeList{} }
func (*PolicyNodeList) ProtoMessage()               {}
func (*PolicyNodeList) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{6} }

func (m *PolicyNodeSpec) Reset()                    { *m = PolicyNodeSpec{} }
func (*PolicyNodeSpec) ProtoMessage()               {}
func (*PolicyNodeSpec) Descriptor() ([]byte, []int) { return fileDescriptorGenerated, []int{7} }

func init() {
	proto.RegisterType((*ClusterPolicies)(nil), "github.com.google.nomos.pkg.api.policyhierarchy.v1.ClusterPolicies")
	proto.RegisterType((*ClusterPolicy)(nil), "github.com.google.nomos.pkg.api.policyhierarchy.v1.ClusterPolicy")
	proto.RegisterType((*ClusterPolicyList)(nil), "github.com.google.nomos.pkg.api.policyhierarchy.v1.ClusterPolicyList")
	proto.RegisterType((*ClusterPolicySpec)(nil), "github.com.google.nomos.pkg.api.policyhierarchy.v1.ClusterPolicySpec")
	proto.RegisterType((*Policies)(nil), "github.com.google.nomos.pkg.api.policyhierarchy.v1.Policies")
	proto.RegisterType((*PolicyNode)(nil), "github.com.google.nomos.pkg.api.policyhierarchy.v1.PolicyNode")
	proto.RegisterType((*PolicyNodeList)(nil), "github.com.google.nomos.pkg.api.policyhierarchy.v1.PolicyNodeList")
	proto.RegisterType((*PolicyNodeSpec)(nil), "github.com.google.nomos.pkg.api.policyhierarchy.v1.PolicyNodeSpec")
}
func (m *ClusterPolicies) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterPolicies) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ClusterRolesV1) > 0 {
		for _, msg := range m.ClusterRolesV1 {
			dAtA[i] = 0x12
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.ClusterRoleBindingsV1) > 0 {
		for _, msg := range m.ClusterRoleBindingsV1 {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.PodSecurityPoliciesV1Beta1) > 0 {
		for _, msg := range m.PodSecurityPoliciesV1Beta1 {
			dAtA[i] = 0x22
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *ClusterPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterPolicy) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ObjectMeta.Size()))
	n1, err := m.ObjectMeta.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	dAtA[i] = 0x12
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Spec.Size()))
	n2, err := m.Spec.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	return i, nil
}

func (m *ClusterPolicyList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterPolicyList) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ListMeta.Size()))
	n3, err := m.ListMeta.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	if len(m.Items) > 0 {
		for _, msg := range m.Items {
			dAtA[i] = 0x12
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *ClusterPolicySpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClusterPolicySpec) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Policies.Size()))
	n4, err := m.Policies.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n4
	if m.UnmanagedNamespacesV1 != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(m.UnmanagedNamespacesV1.Size()))
		n5, err := m.UnmanagedNamespacesV1.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	return i, nil
}

func (m *Policies) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Policies) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.RolesV1) > 0 {
		for _, msg := range m.RolesV1 {
			dAtA[i] = 0xa
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.RoleBindingsV1) > 0 {
		for _, msg := range m.RoleBindingsV1 {
			dAtA[i] = 0x12
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.ResourceQuotaV1 != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintGenerated(dAtA, i, uint64(m.ResourceQuotaV1.Size()))
		n6, err := m.ResourceQuotaV1.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n6
	}
	return i, nil
}

func (m *PolicyNode) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PolicyNode) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ObjectMeta.Size()))
	n7, err := m.ObjectMeta.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n7
	dAtA[i] = 0x12
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Spec.Size()))
	n8, err := m.Spec.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n8
	return i, nil
}

func (m *PolicyNodeList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PolicyNodeList) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.ListMeta.Size()))
	n9, err := m.ListMeta.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n9
	if len(m.Items) > 0 {
		for _, msg := range m.Items {
			dAtA[i] = 0x12
			i++
			i = encodeVarintGenerated(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *PolicyNodeSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PolicyNodeSpec) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0x8
	i++
	if m.Policyspace {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i++
	dAtA[i] = 0x12
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Parent)))
	i += copy(dAtA[i:], m.Parent)
	dAtA[i] = 0x1a
	i++
	i = encodeVarintGenerated(dAtA, i, uint64(m.Policies.Size()))
	n10, err := m.Policies.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n10
	return i, nil
}

func encodeFixed64Generated(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Generated(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ClusterPolicies) Size() (n int) {
	var l int
	_ = l
	if len(m.ClusterRolesV1) > 0 {
		for _, e := range m.ClusterRolesV1 {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.ClusterRoleBindingsV1) > 0 {
		for _, e := range m.ClusterRoleBindingsV1 {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.PodSecurityPoliciesV1Beta1) > 0 {
		for _, e := range m.PodSecurityPoliciesV1Beta1 {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *ClusterPolicy) Size() (n int) {
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *ClusterPolicyList) Size() (n int) {
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *ClusterPolicySpec) Size() (n int) {
	var l int
	_ = l
	l = m.Policies.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if m.UnmanagedNamespacesV1 != nil {
		l = m.UnmanagedNamespacesV1.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *Policies) Size() (n int) {
	var l int
	_ = l
	if len(m.RolesV1) > 0 {
		for _, e := range m.RolesV1 {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if len(m.RoleBindingsV1) > 0 {
		for _, e := range m.RoleBindingsV1 {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	if m.ResourceQuotaV1 != nil {
		l = m.ResourceQuotaV1.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *PolicyNode) Size() (n int) {
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *PolicyNodeList) Size() (n int) {
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *PolicyNodeSpec) Size() (n int) {
	var l int
	_ = l
	n += 2
	l = len(m.Parent)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Policies.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func sovGenerated(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ClusterPolicies) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ClusterPolicies{`,
		`ClusterRolesV1:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ClusterRolesV1), "ClusterRole", "k8s_io_api_rbac_v1.ClusterRole", 1), `&`, ``, 1) + `,`,
		`ClusterRoleBindingsV1:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ClusterRoleBindingsV1), "ClusterRoleBinding", "k8s_io_api_rbac_v1.ClusterRoleBinding", 1), `&`, ``, 1) + `,`,
		`PodSecurityPoliciesV1Beta1:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.PodSecurityPoliciesV1Beta1), "PodSecurityPolicy", "k8s_io_api_extensions_v1beta1.PodSecurityPolicy", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ClusterPolicy) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ClusterPolicy{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(this.ObjectMeta.String(), "ObjectMeta", "k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "ClusterPolicySpec", "ClusterPolicySpec", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ClusterPolicyList) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ClusterPolicyList{`,
		`ListMeta:` + strings.Replace(strings.Replace(this.ListMeta.String(), "ListMeta", "k8s_io_apimachinery_pkg_apis_meta_v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Items), "ClusterPolicy", "ClusterPolicy", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ClusterPolicySpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ClusterPolicySpec{`,
		`Policies:` + strings.Replace(strings.Replace(this.Policies.String(), "ClusterPolicies", "ClusterPolicies", 1), `&`, ``, 1) + `,`,
		`UnmanagedNamespacesV1:` + strings.Replace(fmt.Sprintf("%v", this.UnmanagedNamespacesV1), "ConfigMap", "k8s_io_api_core_v1.ConfigMap", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Policies) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Policies{`,
		`RolesV1:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.RolesV1), "Role", "k8s_io_api_rbac_v1.Role", 1), `&`, ``, 1) + `,`,
		`RoleBindingsV1:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.RoleBindingsV1), "RoleBinding", "k8s_io_api_rbac_v1.RoleBinding", 1), `&`, ``, 1) + `,`,
		`ResourceQuotaV1:` + strings.Replace(fmt.Sprintf("%v", this.ResourceQuotaV1), "ResourceQuota", "k8s_io_api_core_v1.ResourceQuota", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PolicyNode) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PolicyNode{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(this.ObjectMeta.String(), "ObjectMeta", "k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "PolicyNodeSpec", "PolicyNodeSpec", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PolicyNodeList) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PolicyNodeList{`,
		`ListMeta:` + strings.Replace(strings.Replace(this.ListMeta.String(), "ListMeta", "k8s_io_apimachinery_pkg_apis_meta_v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Items), "PolicyNode", "PolicyNode", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PolicyNodeSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PolicyNodeSpec{`,
		`Policyspace:` + fmt.Sprintf("%v", this.Policyspace) + `,`,
		`Parent:` + fmt.Sprintf("%v", this.Parent) + `,`,
		`Policies:` + strings.Replace(strings.Replace(this.Policies.String(), "Policies", "Policies", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ClusterPolicies) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterPolicies: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterPolicies: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterRolesV1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterRolesV1 = append(m.ClusterRolesV1, k8s_io_api_rbac_v1.ClusterRole{})
			if err := m.ClusterRolesV1[len(m.ClusterRolesV1)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClusterRoleBindingsV1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClusterRoleBindingsV1 = append(m.ClusterRoleBindingsV1, k8s_io_api_rbac_v1.ClusterRoleBinding{})
			if err := m.ClusterRoleBindingsV1[len(m.ClusterRoleBindingsV1)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PodSecurityPoliciesV1Beta1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PodSecurityPoliciesV1Beta1 = append(m.PodSecurityPoliciesV1Beta1, k8s_io_api_extensions_v1beta1.PodSecurityPolicy{})
			if err := m.PodSecurityPoliciesV1Beta1[len(m.PodSecurityPoliciesV1Beta1)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterPolicyList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterPolicyList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterPolicyList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, ClusterPolicy{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClusterPolicySpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClusterPolicySpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClusterPolicySpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Policies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Policies.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnmanagedNamespacesV1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UnmanagedNamespacesV1 == nil {
				m.UnmanagedNamespacesV1 = &k8s_io_api_core_v1.ConfigMap{}
			}
			if err := m.UnmanagedNamespacesV1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Policies) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Policies: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Policies: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RolesV1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RolesV1 = append(m.RolesV1, k8s_io_api_rbac_v1.Role{})
			if err := m.RolesV1[len(m.RolesV1)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoleBindingsV1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoleBindingsV1 = append(m.RoleBindingsV1, k8s_io_api_rbac_v1.RoleBinding{})
			if err := m.RoleBindingsV1[len(m.RoleBindingsV1)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceQuotaV1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ResourceQuotaV1 == nil {
				m.ResourceQuotaV1 = &k8s_io_api_core_v1.ResourceQuota{}
			}
			if err := m.ResourceQuotaV1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PolicyNode) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PolicyNode: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PolicyNode: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PolicyNodeList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PolicyNodeList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PolicyNodeList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, PolicyNode{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PolicyNodeSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PolicyNodeSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PolicyNodeSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Policyspace", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Policyspace = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Parent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Policies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Policies.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowGenerated
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipGenerated(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthGenerated = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("github.com/google/nomos/pkg/api/policyhierarchy/v1/generated.proto", fileDescriptorGenerated)
}

var fileDescriptorGenerated = []byte{
	// 833 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0x8e, 0xd3, 0xee, 0x6e, 0x98, 0xb2, 0x09, 0xb8, 0x5a, 0x14, 0x22, 0xad, 0xb3, 0xf8, 0xb0,
	0xda, 0xcb, 0x8e, 0xf1, 0xf2, 0x21, 0x0e, 0x08, 0x09, 0x47, 0x1c, 0x90, 0xd8, 0x12, 0x5c, 0xd1,
	0x03, 0x42, 0xa2, 0x13, 0x67, 0xea, 0x4c, 0x1b, 0x7b, 0xcc, 0xcc, 0x38, 0x22, 0xe2, 0x82, 0xf8,
	0x05, 0x15, 0xbf, 0xaa, 0xc7, 0x4a, 0x70, 0x28, 0x20, 0x55, 0x34, 0xfc, 0x03, 0x7e, 0x01, 0x9a,
	0xf1, 0x24, 0xfe, 0x88, 0x43, 0xd9, 0x56, 0xea, 0xcd, 0x9e, 0x79, 0x9f, 0xe7, 0x79, 0x9f, 0x79,
	0x3f, 0x80, 0x17, 0x12, 0x31, 0x49, 0x47, 0x30, 0xa0, 0x91, 0x13, 0x52, 0x1a, 0x4e, 0xb1, 0x13,
	0xd3, 0x88, 0x72, 0x27, 0x39, 0x09, 0x1d, 0x94, 0x10, 0x27, 0xa1, 0x53, 0x12, 0xcc, 0x27, 0x04,
	0x33, 0xc4, 0x82, 0xc9, 0xdc, 0x99, 0xb9, 0x4e, 0x88, 0x63, 0xcc, 0x90, 0xc0, 0x63, 0x98, 0x30,
	0x2a, 0xa8, 0xf9, 0x22, 0xe7, 0x80, 0x19, 0x07, 0x54, 0x1c, 0x30, 0x39, 0x09, 0x21, 0x4a, 0x08,
	0xac, 0x70, 0xc0, 0x99, 0xdb, 0x7b, 0x5e, 0xd2, 0x0d, 0xa9, 0xa3, 0xa8, 0x46, 0xe9, 0x91, 0xfa,
	0x53, 0x3f, 0xea, 0x2b, 0x93, 0xe8, 0xd9, 0x27, 0x1f, 0x71, 0x48, 0xa8, 0xca, 0x28, 0xa0, 0x0c,
	0xd7, 0xa4, 0xd1, 0x7b, 0x5e, 0x88, 0xc1, 0x3f, 0x08, 0x1c, 0x73, 0x42, 0x63, 0xee, 0xcc, 0xdc,
	0x11, 0x16, 0x68, 0x3d, 0xbc, 0x48, 0xc9, 0x46, 0x28, 0xa8, 0xa3, 0x7c, 0x3f, 0x8f, 0x89, 0x50,
	0x30, 0x21, 0x31, 0x66, 0xf3, 0xe5, 0xcb, 0x70, 0x27, 0xc2, 0x02, 0xd5, 0xa1, 0x9c, 0x4d, 0x28,
	0x96, 0xc6, 0x82, 0x44, 0x78, 0x0d, 0xf0, 0xe1, 0x75, 0x00, 0x1e, 0x4c, 0x70, 0x84, 0xd6, 0x70,
	0xef, 0x6d, 0xc2, 0xa5, 0x82, 0x4c, 0x1d, 0x12, 0x0b, 0x2e, 0x58, 0x15, 0x64, 0xff, 0xbc, 0x05,
	0x3a, 0x83, 0x69, 0xca, 0x05, 0x66, 0x43, 0x59, 0x17, 0x82, 0xb9, 0xf9, 0x1d, 0x68, 0x07, 0xd9,
	0x91, 0x4f, 0xa7, 0x98, 0x1f, 0xb8, 0xdd, 0xe6, 0x93, 0xad, 0x67, 0x3b, 0x2f, 0xfa, 0x30, 0x53,
	0x50, 0x55, 0x94, 0x8f, 0x04, 0x67, 0x2e, 0x1c, 0xe4, 0x91, 0xde, 0x5b, 0x67, 0x97, 0xfd, 0xc6,
	0xe2, 0xb2, 0xdf, 0x1e, 0x94, 0xe0, 0x7e, 0x85, 0xce, 0xfc, 0x11, 0x3c, 0x2a, 0x9c, 0x78, 0x24,
	0x1e, 0x93, 0x38, 0x94, 0x3a, 0x5b, 0x4a, 0xe7, 0xe9, 0x75, 0x3a, 0x19, 0xc0, 0x7b, 0xac, 0xe5,
	0x1e, 0x0d, 0xea, 0xc8, 0xfc, 0x7a, 0x0d, 0xf3, 0xd4, 0x00, 0xdd, 0x84, 0x8e, 0xf7, 0x71, 0x90,
	0x32, 0x22, 0xe6, 0xca, 0xf5, 0xfc, 0xc0, 0xf5, 0x64, 0x5b, 0x74, 0xb7, 0x55, 0x02, 0xef, 0x16,
	0x13, 0xc8, 0x9b, 0x07, 0xea, 0xe6, 0x81, 0xc3, 0x2a, 0xdc, 0xb3, 0x75, 0x2a, 0xbd, 0xea, 0x15,
	0x91, 0x86, 0x15, 0xb7, 0xbf, 0x51, 0xd5, 0xfe, 0xc3, 0x00, 0x0f, 0x8b, 0x45, 0x98, 0x9b, 0x87,
	0xa0, 0x25, 0xfb, 0x69, 0x8c, 0x04, 0xea, 0x1a, 0x4f, 0x8c, 0x4a, 0x4e, 0xab, 0xf2, 0x2e, 0x67,
	0x8a, 0x43, 0x19, 0x2d, 0x9f, 0xe9, 0xcb, 0xd1, 0x31, 0x0e, 0xc4, 0x4b, 0x2c, 0x90, 0x67, 0xea,
	0x9c, 0x40, 0x7e, 0xe6, 0xaf, 0x58, 0xcd, 0x10, 0x6c, 0xf3, 0x04, 0x07, 0xdd, 0xa6, 0x62, 0xff,
	0x0c, 0xbe, 0xfa, 0xd4, 0xc2, 0x52, 0xca, 0xfb, 0x09, 0x0e, 0xbc, 0xd7, 0xb5, 0xe4, 0xb6, 0xfc,
	0xf3, 0x95, 0x80, 0xfd, 0xbb, 0x01, 0xde, 0x2c, 0x45, 0x7e, 0x41, 0xb8, 0x30, 0xbf, 0x5d, 0x33,
	0x08, 0xff, 0x9f, 0x41, 0x89, 0x56, 0xf6, 0xde, 0xd0, 0x5a, 0xad, 0xe5, 0x49, 0xc1, 0xdc, 0x11,
	0xb8, 0x47, 0x04, 0x8e, 0xb8, 0x6e, 0xdc, 0x4f, 0x6f, 0xed, 0xce, 0x7b, 0xa8, 0xd5, 0xee, 0x7d,
	0x2e, 0x79, 0xfd, 0x8c, 0xde, 0xfe, 0xa7, 0xea, 0x4d, 0xfa, 0x36, 0xbf, 0x07, 0xad, 0x44, 0xd7,
	0x5e, 0x7b, 0x1b, 0xdc, 0x36, 0x01, 0x82, 0x79, 0x6e, 0x78, 0x79, 0xe2, 0xaf, 0x64, 0xcc, 0x63,
	0xb0, 0x9b, 0xc6, 0x11, 0x8a, 0x51, 0x88, 0xc7, 0x7b, 0x28, 0xc2, 0x3c, 0x41, 0x01, 0xe6, 0xba,
	0xb8, 0x8f, 0x8b, 0xed, 0x2c, 0xf7, 0xa5, 0x62, 0xa7, 0xf1, 0x11, 0x09, 0x5f, 0xa2, 0xc4, 0x7b,
	0x5b, 0x8e, 0xd0, 0xd7, 0xeb, 0xe8, 0x03, 0xd7, 0xaf, 0x23, 0xb5, 0x7f, 0x69, 0x82, 0x55, 0x0a,
	0xe6, 0x00, 0x3c, 0x60, 0x7a, 0x49, 0x18, 0xea, 0xad, 0xbb, 0x75, 0xc3, 0xab, 0x46, 0xb0, 0xa3,
	0xf3, 0x7f, 0xb0, 0x5c, 0x0b, 0x4b, 0xa4, 0x5c, 0x38, 0xac, 0xbc, 0x08, 0xfe, 0x63, 0xe1, 0x14,
	0x37, 0xc0, 0x6a, 0xe1, 0x54, 0x46, 0xbf, 0x42, 0x67, 0x1e, 0x82, 0x0e, 0xc3, 0x9c, 0xa6, 0x2c,
	0xc0, 0x5f, 0xa5, 0x54, 0x20, 0xb5, 0x6a, 0xe4, 0xd3, 0xbc, 0x53, 0xf7, 0x34, 0x7e, 0x31, 0xd4,
	0xdb, 0x5d, 0x5c, 0xf6, 0x3b, 0x7e, 0x19, 0xed, 0x57, 0xe9, 0xec, 0xdf, 0x0c, 0x00, 0xb2, 0x16,
	0xd8, 0xa3, 0x63, 0x7c, 0x07, 0xf3, 0x3b, 0x2e, 0xcd, 0xaf, 0x77, 0x93, 0x06, 0xcb, 0xf3, 0xdd,
	0x38, 0xbc, 0xbf, 0x1a, 0xa0, 0x9d, 0x87, 0xdd, 0xc1, 0xe4, 0x06, 0xe5, 0xc9, 0xfd, 0xe4, 0x76,
	0xbe, 0x36, 0x8c, 0xed, 0x9f, 0x25, 0x57, 0x6a, 0x66, 0x3f, 0x00, 0x3b, 0x19, 0x93, 0x6a, 0x72,
	0x65, 0xac, 0xe5, 0xed, 0x6a, 0xf4, 0xce, 0x30, 0xbf, 0xf2, 0x8b, 0x71, 0xe6, 0x53, 0x70, 0x3f,
	0x41, 0x0c, 0xc7, 0x42, 0xd5, 0xe1, 0x35, 0xaf, 0xad, 0x11, 0xf7, 0x87, 0xea, 0xd4, 0xd7, 0xb7,
	0xe6, 0x71, 0x61, 0x25, 0x64, 0x9d, 0xf7, 0xf1, 0x8d, 0x9d, 0x5d, 0xb3, 0x0b, 0xbc, 0x67, 0x67,
	0x57, 0x56, 0xe3, 0xfc, 0xca, 0x6a, 0x5c, 0x5c, 0x59, 0x8d, 0x9f, 0x16, 0x96, 0x71, 0xb6, 0xb0,
	0x8c, 0xf3, 0x85, 0x65, 0x5c, 0x2c, 0x2c, 0xe3, 0xaf, 0x85, 0x65, 0x9c, 0xfe, 0x6d, 0x35, 0xbe,
	0x69, 0xce, 0xdc, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x50, 0x61, 0xf4, 0x89, 0xef, 0x09, 0x00,
	0x00,
}
