kind: ClusterRoleBinding # not defined in rbac.yaml, so not syncable
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: not-syncable-clusterrolebinding
subjects:
- kind: User
  name: alice@acme.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: acme-admin
  apiGroup: rbac.authorization.k8s.io
