kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alice-rolebinding # duplicates alice-rolebinding.yaml in parent directory
subjects:
- kind: User
  name: alice@acme.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: acme-admin
  apiGroup: rbac.authorization.k8s.io
